### ISSUE TITLE
ERROR: Download page changed its syntax or is not parsable

### ISSUE THREAD

**Issue by fd-origin** [ubuntu/ubuntu-make#146] opened 2015-08-30 09:32 UTC
I couldn't download visual-studio-code. This is probably similar to issue #135.

**Comment by didrocks** [comment] 2015-08-31 07:47
Thanks for opening this bug report and help making Ubuntu make better!
I can't reproduce your issue here, and neither our central tests do. I wonder if the issue you experienced was temporary only, or due to some mirrors/specific page?

Do you mind running a download with:
$ umake -vv web visual-studio-code
and paste the results here? Also, in what lang is your system? That would maybe redirect you to somewhere not supported.

Thanks for keeping me posted, and sorry for the issue you experienced here!

**Comment by fd-origin** [comment] 2015-08-31 10:32
I'm trying to download VSCode for my Ubuntu 14.10.

I ran $ umake -vv web visual-studio-code  and i got this:

DEBUG: Installation path provided. Checking if exists.
DEBUG: Download application provider page
INFO: Start downloading DownloadItem(url='https://code.visualstudio.com', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False) in memory
INFO: Starting new HTTPS connection (1): code.visualstudio.com
DEBUG: "GET / HTTP/1.1" 200 4651
DEBUG: Deliver download update: {'https://code.visualstudio.com': {'size': 4651, 'current': 0}} of 4651
DEBUG: Deliver download update: {'https://code.visualstudio.com': {'size': 4651, 'current': 4651}} of 4651
INFO: https://code.visualstudio.com download finished
INFO: All pending downloads for [DownloadItem(url='https://code.visualstudio.com', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False)] done
DEBUG: Parse download metadata
ERROR: Download page changed its syntax or is not parsable

**Comment by didrocks** [comment] 2015-08-31 10:41
Oh, I think I know what happens. 14.10 isn't supported by ubuntu anymore (support period for intermediate release is only 9 months) and we don't support Ubuntu Make there either as you are running an Ubuntu version that doesn't have security support. You should really upgrade to 15.04 or use the LTS version.

If you really want to continue using 14.10, but still upgrade to newer Ubuntu Make, you can add the Ubuntu Make ppa: ppa:ubuntu-desktop/ubuntu-make and rollback to add the LTS version for it: changing
/etc/apt/sources.list.d/ubuntu-desktop-ubuntu-make.list "utopic" to "trusty".
Then upgrade your system to get this version.

I'm marking as invalid as the issue is due to running a version that run its end of line. However, keep me posted that this fixed it for you!

**Closed by didrocks** 2015-08-31 10:41 UTC

**Comment by fd-origin** [comment] 2015-08-31 10:44
I see. Alright i'm gonna try that. Thanks for responding.
