### ISSUE TITLE
Can't install android on lasted version

### ISSUE THREAD

**Issue by Nymerea** [ubuntu/ubuntu-make#75] opened 2015-02-20 11:14 UTC
Hello guys,

I have a fresh install on Ubuntu 14.04 LTS and I have install the ppa. ( sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make )

When I lunch android installation : morgan@laptop:~$ umake android
I have this error : 

[I Accept (a)/I don't accept (N)] a
Downloading and installing requirements                                        |
ERROR: Unhandled exception#################################################### |
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 154, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 262, in get_progress
    self.pbar.update(progress)
  File "/usr/lib/python3/dist-packages/progressbar/__init__.py", line 271, in update
    raise ValueError('Value out of range')
ValueError: Value out of range

**Comment by didrocks** [comment] 2015-02-20 11:40
Hi!
Which ubuntu version are you using? Also, can you report the version of python3-progress?
$ apt-cache policy python3-progressbar

**Comment by Nymerea** [comment] 2015-02-20 14:38
Hello, I use Ubuntu 14.04.2 LTS

My version of python3-progress is : 

python3-progressbar:
  Installed: 2.3-1
  Candidate: 2.3-1
  Version table:
 *** 2.3-1 0
        500 http://ie.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
        100 /var/lib/dpkg/status

**Comment by didrocks** [comment] 2015-02-20 14:41
Thanks! I'll give it a look (probably on Monday if nobody beats me to it), we have the same version in vivid and the parameters are all supported.

Please ensure you don't have any local version of python3-progress on your system (sudo pip install… or anything like that). I guess you get it reliably? (like after a second download as well?)

**Comment by Nymerea** [comment] 2015-02-20 14:49
Like I said, I had try the install on a very fresh ubuntu 14.04 LTS (I had just make a apt-get update before try to install android studio).

For moment I have install AndroidStudio manually

**Comment by Tinche** [comment] 2015-02-20 15:19
FWIW I tried doing the installation in Docker using the ubuntu:14.04 image, works fine. BTW we should probably add python3-setuptools to the list of dependencies. :)

**Comment by didrocks** [comment] 2015-02-20 15:30
Thanks Tinche for checking! Nymerea, if you have some time, would be interested that you run your command with: umake -vv android and paste the full output here, thanks!

@Tinche: python3-setuptools is a build dependency only isn't it? (Not sure this has room in requirements.txt, but it's listed in debian/control)

**Comment by Nymerea** [comment] 2015-02-20 15:36
Now I have installed manually android studio, the installation with umake work fine, weird !

**Comment by didrocks** [comment] 2015-02-20 15:44
urgh, closing the issue then as we can't reproduce and you can't as well. I wonder if we end up with a division giving more then 100% and such, you got the invalid value traceback. I think I'll cap it soon.

Do not hesitate to reopen in case you notice something similar, enjoy android dev on ubuntu! :)

**Closed by didrocks** 2015-02-20 15:44 UTC

**Comment by Tinche** [comment] 2015-02-20 23:00
@didrocks the Ubuntu docker image is probably much more minimal than a desktop install. Installing Ubuntu Make from the ppa, just running it results in an import error of pkg_resources, which can be solved by installing python3-setuptools. So it's a runtime dependency too, looks like.

**Comment by didrocks** [comment] 2015-02-23 09:21
Interesting, I think it's more an issue on a dpkg trigger though on a lower layer. I'm pinging our python packager so that this can be fixed at the correct place.

**Comment by pjdelport** [comment] 2015-07-08 21:36
This, or a variant of this, still seems to be happening: #123
