### ISSUE TITLE
What insanity is this?

### ISSUE THREAD

**Issue by trans** [ubuntu/ubuntu-make#197] opened 2015-11-29 15:13 UTC
This is an official Ubuntu project? Why is it necessary to have a separate package management system for the "common needs for developers" -- that the apt-get system wouldn't handle far better? the conflation of complexity just seems insane to me. What gives?

**Comment by Tinche** [comment] 2015-11-29 20:11
Honestly, if the apt-get system was good for this all of these would already be in the repositories.

**Comment by didrocks** [comment] 2015-11-30 07:02
I'm closing this issue as it's not a bug nor a real question. If you want the information on why this official Ubuntu project exists, you will find them at Ubuntu Online Summit past session, or in this wiki page: https://wiki.ubuntu.com/ubuntu-make. You will see there the difference between what this projects offers and the default ubuntu policy for packages.

**Closed by didrocks** 2015-11-30 07:02 UTC

**Comment by trans** [comment] 2015-11-30 14:44
Thanks for the link. It is a *very real* question, though.

I worry about the continued erosion of the package system. We have seen the rise of per-language systems (gems, npm, etc.) and recently "core" applications with snappy, and here a separation for developer tools. If the fragmentation continues, how much worse will it get? We might end up right back at Windows-style installs -- it isn't hard to imagine at this point, for instance, Google releasing it's own package installer for it's own software.

I would think that ultimate goal of Ubuntu package management is the ability to open up the "Software Center", find the software desired, and click "Install". Although as a developer, I often use the command line, if this GUI method isn't possible then the system is essentially broken. 

@Tinche If the apt-get system isn't good enough, then wouldn't it make more sense to improve it so it were? However, I suspect there is little if anything the debian package manager can't handle in this regard. (e.g. https://paolorotolo.github.io/android-studio/)
