### ISSUE TITLE
Dart and Flutter-SDK fails during instalation

### ISSUE THREAD

**Issue by sezaru** [ubuntu/ubuntu-make#625] opened 2020-04-27 22:26 UTC
Running latest version of ubuntu-make (and also master version) trying to install Dart will return this error:
```python
$ umake dart
Choose installation path: /home/sezdocs/.local/share/umake/dart/dart-sdk
ERROR: https://storage.googleapis.com/dart-archive/channels/stable/release/2.9.0/sdk/dartsdk-linux-x64-release.zip.sha256sum couldn't finish download: 404 Client Error: Not Found for url: https://storage.googleapis.com/dart-archive/channels/stable/release/2.9.0/sdk/dartsdk-linux-x64-release.zip.sha256sum
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/snap/ubuntu-make/678/lib/python3.6/site-packages/umake/tools.py", line 159, in wrapper
    function(*args, **kwargs)
  File "/snap/ubuntu-make/678/lib/python3.6/site-packages/umake/frameworks/dart.py", line 87, in get_sha_and_start_download
    checksum = res.buffer.getvalue().decode('utf-8').split()[0]
AttributeError: 'NoneType' object has no attribute 'getvalue'
```

Also, trying to install the flutter-sdk will return another error:
```python
$ umake dart flutter-sdk
Choose installation path: /home/sezdocs/.local/share/umake/dart/flutter-sdk
Downloading and installing requirements                                        |
ERROR: https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.12.13+hotfix.9-pre.2-stable.tar.xz couldn't finish download: 404 Client Error: Not Found for url: https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.12.13+hotfix.9-pre.2-stable.tar.xz
100% |#########################################################################|
ERROR: 404 Client Error: Not Found for url: https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.12.13+hotfix.9-pre.2-stable.tar.xz
```

**Comment by LyzardKing** [comment] 2020-04-28 07:57
Hi, thanks for the notification.
The issue is that there is no "static" link to the releases of dart and flutter, so the parsing I used previously will not work anymore.

**Comment by LyzardKing** [comment] 2020-04-29 18:08
@sezaru it should be fixed in https://github.com/ubuntu/ubuntu-make/commit/312bdd8e4028b31823166af56a613f2c97012921

**Closed by LyzardKing** 2020-04-29 18:08 UTC
