### ISSUE TITLE
UnboundLocalError: local variable 'url_found' referenced before assignment

### ISSUE THREAD

**Issue by ermlauri** [ubuntu/ubuntu-make#586] opened 2018-12-30 18:29 UTC
I'm trying to create a Ubuntu 18.04.1 live USB in Cubic and install Eclipse:
```
umake ide eclipse-jee
```
but umake (version 18.09) gives following error:
```
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 249, in get_metadata_and_check_license
    (download, in_download) = self.parse_download_link(line_content, in_download)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 103, in parse_download_link
    return (url_found, in_download)
UnboundLocalError: local variable 'url_found' referenced before assignment
```

Tried also:
```
$ git clone https://github.com/ubuntu/ubuntu-make
$ cd ubuntu-make
$ bin/umake <your-command>
```
with same results.

**Comment by JavaCafe01** [comment] 2019-01-02 22:47
I'm also getting this error when trying to install eclipse.

**Comment by LyzardKing** [comment] 2019-01-03 09:08
Do you have the latest version of umake?
I recently updated the eclipse downloaded.
If it still fails, could you run 'umake -vv ide eclipse' and paste the log
somewhere?

**Comment by ymeramees** [comment] 2019-01-03 20:05
I'm using latest version from snap (18.09), checked today, that no updates were provided.
`umake -vv ide eclipse-jee` gives following result, in Pastebin:
https://pastebin.com/Mags3L5h

**Comment by JavaCafe01** [comment] 2019-01-03 20:07
I have version 18.09 also, and here's my [log](https://docs.google.com/document/d/1b7P1OmjXH73_qXac-Ar9v-5Pir5iydtcvwyn5oS1MLw/edit?usp=sharing).

**Comment by LyzardKing** [comment] 2019-01-03 20:17
That's very strange.The version you have should not have that code in it..
I can't reproduce the issue.
@JavaCafe01 Could you also tell me the output of "apt policy ubuntu-make"?
@ymeramees At the moment the snap is not working properly. You could try again from the repo

**Comment by LyzardKing** [comment] 2019-01-03 21:06
This issue should be fixed in https://github.com/ubuntu/ubuntu-make/commit/9ea79916759cacb0cfd5dfe8fc87246215ea41e8
Let me know if it works for you!

**Comment by LyzardKing** [comment] 2019-01-04 15:51
The fix is now in the ppa as well.

**Comment by JavaCafe01** [comment] 2019-01-05 04:57
It works, thanks!

**Closed as completed** 2019-01-05 10:27 UTC
