### ISSUE TITLE
Problem installing arduino ide on 14.04

### ISSUE THREAD

**Issue by rkandilarov** [ubuntu/ubuntu-make#385] opened 2016-11-24 19:28 UTC
Hello guys!

I have problem installing arduino on 14.04 .

Any ideas?

```
lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```
```
umake --version
16.11.1
```
```
LANG=C umake -vv ide arduino
INFO: Logging level set to DEBUG
DEBUG: New framework module: umake.frameworks.android
DEBUG: Found category: AndroidCategory
INFO: Create a new apt cache
DEBUG: Check if ['clang'] is installed
INFO: clang isn't installed
DEBUG: Opening None
INFO: No configuration file found
DEBUG: Attach framework AndroidNDK to Android
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk', 'libncurses5:i386', 'libstdc++6:i386', 'zlib1g:i386'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework AndroidSDK to Android
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk', 'libncurses5:i386', 'libstdc++6:i386', 'zlib1g:i386'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework AndroidStudio to Android
DEBUG: Check if [] is installed
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
DEBUG: Attach framework EclipseADTForRemoval to Android
DEBUG: New framework module: umake.frameworks.baseinstaller
DEBUG: New framework module: umake.frameworks.dart
DEBUG: Found category: DartCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework DartLang to Dart
DEBUG: Check if [] is installed
INFO: Don't register Dart Editor as it's not installable on this configuration.
DEBUG: Attach framework DartLangEditorRemoval to Dart
DEBUG: New framework module: umake.frameworks.games
DEBUG: Found category: GamesCategory
DEBUG: Check if ['libxtst6:i386', 'libxext6:i386', 'libxi6:i386', 'libncurses5:i386', 'libxt6:i386', 'libxpm4:i386', 'libxmu6:i386', 'libgtk2.0-0:i386', 'libatk1.0-0:i386', 'libc6:i386', 'libcairo2:i386', 'libexpat1:i386', 'libfontconfig1:i386', 'libfreetype6:i386', 'libglib2.0-0:i386', 'libice6:i386', 'libpango1.0-0:i386', 'libpng12-0:i386', 'libsm6:i386', 'libxau6:i386', 'libxcursor1:i386', 'libxdmcp6:i386', 'libxfixes3:i386', 'libx11-6:i386', 'libxinerama1:i386', 'libxrandr2:i386', 'libxrender1:i386', 'zlib1g:i386', 'libnss3-1d:i386', 'libnspr4-0d:i386', 'libcurl3:i386', 'libasound2:i386'] is installed
INFO: libxmu6:i386 isn't installed
INFO: libpango1.0-0:i386 isn't installed
INFO: libnss3-1d:i386 isn't installed
INFO: libnspr4-0d:i386 isn't installed
INFO: libcurl3:i386 isn't installed
DEBUG: Attach framework Stencyl to Games
DEBUG: Check if [] is installed
DEBUG: Attach framework Superpowers to Games
DEBUG: Check if [] is installed
DEBUG: Attach framework Twine to Games
DEBUG: Attach framework Unity3D to Games
DEBUG: New framework module: umake.frameworks.go
DEBUG: Found category: GoCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework GoLang to Go
DEBUG: New framework module: umake.frameworks.ide
DEBUG: Found category: IdeCategory
DEBUG: Attach framework Arduino to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework Atom to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework BaseNetBeans to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework CLion to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework DataGrip to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework EclipseCPP to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework EclipseJEE to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework EclipseJava to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework EclipsePHP to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework Idea to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework IdeaUltimate to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework LightTable to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework PhpStorm to IDE
DEBUG: Check if ['python', 'python3'] is installed
DEBUG: Attach framework PyCharm to IDE
DEBUG: Check if ['python', 'python3'] is installed
DEBUG: Attach framework PyCharmEducational to IDE
DEBUG: Check if ['python', 'python3'] is installed
DEBUG: Attach framework PyCharmProfessional to IDE
DEBUG: Check if ['ruby'] is installed
DEBUG: Attach framework RubyMine to IDE
DEBUG: Attach framework SpringToolsSuite to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework SublimeText to IDE
DEBUG: Check if ['libgtk2.0-0'] is installed
DEBUG: Attach framework VisualStudioCode to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework WebStorm to IDE
DEBUG: New framework module: umake.frameworks.kotlin
DEBUG: Found category: KotlinCategory
DEBUG: Check if ['openjdk-7-jre | openjdk-8-jre'] is installed
DEBUG: Check if ['openjdk-7-jre'] is installed
DEBUG: Attach framework KotlinLang to Kotlin
DEBUG: New framework module: umake.frameworks.nodejs
DEBUG: Found category: NodejsCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework NodejsLang to Nodejs
DEBUG: New framework module: umake.frameworks.rust
DEBUG: Found category: RustCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework RustLang to Rust
DEBUG: New framework module: umake.frameworks.scala
DEBUG: Found category: ScalaCategory
DEBUG: Check if ['openjdk-7-jre | openjdk-8-jre'] is installed
DEBUG: Check if ['openjdk-7-jre'] is installed
DEBUG: Attach framework ScalaLang to Scala
DEBUG: New framework module: umake.frameworks.swift
DEBUG: Found category: SwiftCategory
DEBUG: Check if ['clang', 'libicu-dev'] is installed
INFO: clang isn't installed
INFO: libicu-dev isn't installed
DEBUG: Attach framework SwiftLang to Swift
DEBUG: New framework module: umake.frameworks.web
DEBUG: Found category: WebCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework FirefoxDev to Web
DEBUG: Check if ['libgtk2.0-0'] is installed
DEBUG: Attach framework VisualStudioCode to Web
DEBUG: Skipping main having no framework
DEBUG: Call run_for on Arduino
DEBUG: Requesting root access
INFO: Logging level set to DEBUG
DEBUG: New framework module: umake.frameworks.android
DEBUG: Found category: AndroidCategory
INFO: Create a new apt cache
DEBUG: Check if ['clang'] is installed
INFO: clang isn't installed
DEBUG: Opening None
INFO: No configuration file found
DEBUG: Attach framework AndroidNDK to Android
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk', 'libncurses5:i386', 'libstdc++6:i386', 'zlib1g:i386'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework AndroidSDK to Android
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk', 'libncurses5:i386', 'libstdc++6:i386', 'zlib1g:i386'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework AndroidStudio to Android
DEBUG: Check if [] is installed
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
DEBUG: Attach framework EclipseADTForRemoval to Android
DEBUG: New framework module: umake.frameworks.baseinstaller
DEBUG: New framework module: umake.frameworks.dart
DEBUG: Found category: DartCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework DartLang to Dart
DEBUG: Check if [] is installed
INFO: Don't register Dart Editor as it's not installable on this configuration.
DEBUG: Attach framework DartLangEditorRemoval to Dart
DEBUG: New framework module: umake.frameworks.games
DEBUG: Found category: GamesCategory
DEBUG: Check if ['libxtst6:i386', 'libxext6:i386', 'libxi6:i386', 'libncurses5:i386', 'libxt6:i386', 'libxpm4:i386', 'libxmu6:i386', 'libgtk2.0-0:i386', 'libatk1.0-0:i386', 'libc6:i386', 'libcairo2:i386', 'libexpat1:i386', 'libfontconfig1:i386', 'libfreetype6:i386', 'libglib2.0-0:i386', 'libice6:i386', 'libpango1.0-0:i386', 'libpng12-0:i386', 'libsm6:i386', 'libxau6:i386', 'libxcursor1:i386', 'libxdmcp6:i386', 'libxfixes3:i386', 'libx11-6:i386', 'libxinerama1:i386', 'libxrandr2:i386', 'libxrender1:i386', 'zlib1g:i386', 'libnss3-1d:i386', 'libnspr4-0d:i386', 'libcurl3:i386', 'libasound2:i386'] is installed
INFO: libxmu6:i386 isn't installed
INFO: libpango1.0-0:i386 isn't installed
INFO: libnss3-1d:i386 isn't installed
INFO: libnspr4-0d:i386 isn't installed
INFO: libcurl3:i386 isn't installed
DEBUG: Attach framework Stencyl to Games
DEBUG: Check if [] is installed
DEBUG: Attach framework Superpowers to Games
DEBUG: Check if [] is installed
DEBUG: Attach framework Twine to Games
DEBUG: Attach framework Unity3D to Games
DEBUG: New framework module: umake.frameworks.go
DEBUG: Found category: GoCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework GoLang to Go
DEBUG: New framework module: umake.frameworks.ide
DEBUG: Found category: IdeCategory
DEBUG: Attach framework Arduino to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework Atom to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework BaseNetBeans to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework CLion to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework DataGrip to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework EclipseCPP to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework EclipseJEE to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework EclipseJava to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework EclipsePHP to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework Idea to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
DEBUG: Attach framework IdeaUltimate to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework LightTable to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework PhpStorm to IDE
DEBUG: Check if ['python', 'python3'] is installed
DEBUG: Attach framework PyCharm to IDE
DEBUG: Check if ['python', 'python3'] is installed
DEBUG: Attach framework PyCharmEducational to IDE
DEBUG: Check if ['python', 'python3'] is installed
DEBUG: Attach framework PyCharmProfessional to IDE
DEBUG: Check if ['ruby'] is installed
DEBUG: Attach framework RubyMine to IDE
DEBUG: Attach framework SpringToolsSuite to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework SublimeText to IDE
DEBUG: Check if ['libgtk2.0-0'] is installed
DEBUG: Attach framework VisualStudioCode to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework WebStorm to IDE
DEBUG: New framework module: umake.frameworks.kotlin
DEBUG: Found category: KotlinCategory
DEBUG: Check if ['openjdk-7-jre | openjdk-8-jre'] is installed
DEBUG: Check if ['openjdk-7-jre'] is installed
DEBUG: Attach framework KotlinLang to Kotlin
DEBUG: New framework module: umake.frameworks.nodejs
DEBUG: Found category: NodejsCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework NodejsLang to Nodejs
DEBUG: New framework module: umake.frameworks.rust
DEBUG: Found category: RustCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework RustLang to Rust
DEBUG: New framework module: umake.frameworks.scala
DEBUG: Found category: ScalaCategory
DEBUG: Check if ['openjdk-7-jre | openjdk-8-jre'] is installed
DEBUG: Check if ['openjdk-7-jre'] is installed
DEBUG: Attach framework ScalaLang to Scala
DEBUG: New framework module: umake.frameworks.swift
DEBUG: Found category: SwiftCategory
DEBUG: Check if ['clang', 'libicu-dev'] is installed
INFO: clang isn't installed
INFO: libicu-dev isn't installed
DEBUG: Attach framework SwiftLang to Swift
DEBUG: New framework module: umake.frameworks.web
DEBUG: Found category: WebCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework FirefoxDev to Web
DEBUG: Check if ['libgtk2.0-0'] is installed
DEBUG: Attach framework VisualStudioCode to Web
DEBUG: Skipping main having no framework
DEBUG: Call run_for on Arduino
DEBUG: No installation path provided. Requesting one.
Choose installation path: /home/administrator/.local/share/umake/ide/arduino
DEBUG: Installation path provided. Checking if exists.
DEBUG: Download application provider page
INFO: Start downloading DownloadItem(url='http://www.arduino.cc/en/Main/Software', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTP connection (1): www.arduino.cc
DEBUG: Setting read timeout to <object object at 0x7f55881940b0>
DEBUG: "GET /en/Main/Software HTTP/1.1" 301 184
INFO: Starting new HTTPS connection (1): www.arduino.cc
DEBUG: Setting read timeout to <object object at 0x7f55881940b0>
DEBUG: "GET /en/Main/Software HTTP/1.1" 200 11833
DEBUG: Deliver download update: {'http://www.arduino.cc/en/Main/Software': {'current': 0, 'size': 11833}} of 11833
DEBUG: Deliver download update: {'http://www.arduino.cc/en/Main/Software': {'current': 8192, 'size': 11833}} of 11833
DEBUG: Deliver download update: {'http://www.arduino.cc/en/Main/Software': {'current': 11833, 'size': 11833}} of 11833
INFO: http://www.arduino.cc/en/Main/Software download finished
INFO: All pending downloads for [DownloadItem(url='http://www.arduino.cc/en/Main/Software', checksum=None, headers=None, ignore_encoding=False, cookies=None)] done
DEBUG: Parse download metadata
INFO: Start downloading DownloadItem(url='http://www.arduino.cc/download_handler.php?f=/arduino-1.6.13-linux64.tar.xz', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTP connection (1): www.arduino.cc
INFO: Start downloading DownloadItem(url='http://downloads.arduino.cc/arduino-1.6.13.md5sum.txt', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTP connection (1): downloads.arduino.cc
DEBUG: Setting read timeout to <object object at 0x7f55881940b0>
DEBUG: Setting read timeout to <object object at 0x7f55881940b0>
DEBUG: "GET /arduino-1.6.13.md5sum.txt HTTP/1.1" 200 None
DEBUG: Deliver download update: {'http://downloads.arduino.cc/arduino-1.6.13.md5sum.txt': {'current': 0, 'size': -1}} of -1
DEBUG: Deliver download update: {'http://downloads.arduino.cc/arduino-1.6.13.md5sum.txt': {'current': 8192, 'size': -1}} of -1
INFO: http://downloads.arduino.cc/arduino-1.6.13.md5sum.txt download finished
DEBUG: "GET /download_handler.php?f=/arduino-1.6.13-linux64.tar.xz HTTP/1.1" 301 184
INFO: Starting new HTTPS connection (1): www.arduino.cc
DEBUG: Setting read timeout to <object object at 0x7f55881940b0>
DEBUG: "GET /download_handler.php?f=/arduino-1.6.13-linux64.tar.xz HTTP/1.1" 302 0
DEBUG: Setting read timeout to <object object at 0x7f55881940b0>
DEBUG: "GET /en/Main/Donate HTTP/1.1" 200 None
DEBUG: Deliver download update: {'http://www.arduino.cc/download_handler.php?f=/arduino-1.6.13-linux64.tar.xz': {'current': 0, 'size': -1}, 'http://downloads.arduino.cc/arduino-1.6.13.md5sum.txt': {'current': 8192, 'size': -1}} of -1
DEBUG: Deliver download update: {'http://www.arduino.cc/download_handler.php?f=/arduino-1.6.13-linux64.tar.xz': {'current': 8192, 'size': -1}, 'http://downloads.arduino.cc/arduino-1.6.13.md5sum.txt': {'current': 8192, 'size': -1}} of -1
DEBUG: Deliver download update: {'http://www.arduino.cc/download_handler.php?f=/arduino-1.6.13-linux64.tar.xz': {'current': 16384, 'size': -1}, 'http://downloads.arduino.cc/arduino-1.6.13.md5sum.txt': {'current': 8192, 'size': -1}} of -1
INFO: http://www.arduino.cc/download_handler.php?f=/arduino-1.6.13-linux64.tar.xz download finished
INFO: All pending downloads for [DownloadItem(url='http://www.arduino.cc/download_handler.php?f=/arduino-1.6.13-linux64.tar.xz', checksum=None, headers=None, ignore_encoding=False, cookies=None), DownloadItem(url='http://downloads.arduino.cc/arduino-1.6.13.md5sum.txt', checksum=None, headers=None, ignore_encoding=False, cookies=None)] done
INFO: Final download url: https://www.arduino.cc/download_handler.php, cookies: <RequestsCookieJar[<Cookie PHPSESSID=ktloucnkbkgd6kjshvjh84iqp2 for www.arduino.cc/>, <Cookie _mcnc=1 for www.arduino.cc/>]>.
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 589, in prepare_to_download_archive
    if not f.result():
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: 'adduser'

```

**Comment by didrocks** [comment] 2016-11-25 06:48
Hey! It seems you are missing the "adduser" command from the adduser debian package. Please reinstall that package (which is part of the default install set)

**Comment by rkandilarov** [comment] 2016-11-25 10:42
>  It seems you are missing the "adduser" command 

Definitely not :)!

```
$ which adduser
/usr/sbin/adduser

$ dpkg -S /usr/sbin/adduser
adduser: /usr/sbin/adduser

$ ls -l /usr/sbin/adduser                                                                                                                 
-rwxr-xr-x 1 root root 35125 Nov  7  2013 /usr/sbin/adduser
```

Any other ideas?

**Comment by didrocks** [comment] 2016-11-25 13:03
Interesting, you are executing the command with a password prompt first, correct? Normally, it should ask you for this.

You can workaround by doing it manually:
`sudo adduser <your_user> dialout`

This is what the failure is attempting to do. Then, you logout/login or refresh with `newgroup` to ensure you have your user in the group and you can restart umake. It will skip this step.

**Comment by rkandilarov** [comment] 2016-11-25 14:08
Thank you @didrocks, that group permission solved the problem!

**Comment by didrocks** [comment] 2016-11-25 14:36
Great! I'm closing the bug as I can't reproduce it, It's a weird error that executing exactly the same command in umake didn't work though :/
Happy that's solved for you :)

**Closed by didrocks** 2016-11-25 14:36 UTC

**Comment by N0rbert** [comment] 2022-11-22 09:43
This issue still happening on Debian 11:

```
d@debian11:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
d@debian11:~$ sudo grep -v ^# /etc/sudoers
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"




root	ALL=(ALL:ALL) ALL

%sudo	ALL=(ALL:ALL) ALL


@includedir /etc/sudoers.d

d@debian11:~$ groups 
d cdrom floppy sudo audio dip video plugdev netdev bluetooth
d@debian11:~$ id
uid=1000(d) gid=1000(d) groups=1000(d),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),108(netdev),110(bluetooth)

d@debian11:~$ sudo apt-get update -qq && sudo apt-get dist-upgrade -y
[...]
d@debian11:~$ sudo apt-get install -y snapd
d@debian11:~$ sudo snap install ubuntu-make --edge --classic
[...]
d@debian11:~$ sudo apt-get install sddm --no-install-recommends --no-install-suggests
[...] # select sddm instead of lightdm
d@debian11:~$ sudo reboot
# login to MATE session after reboot
d@debian11:~$ umake electronics arduino
[sudo] password for d: 
Choose installation path: /home/d/.local/share/umake/electronics/arduino
Downloading and installing requirements                                                                                               |
100% |################################################################################################################################|
Installing Arduino
ERROR: Unhandled exception                                                                                                        #   |
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/snap/ubuntu-make/961/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/snap/ubuntu-make/961/lib/python3.8/site-packages/umake/frameworks/electronics.py", line 48, in _add_to_group
    output = subprocess.check_output(["adduser", user, group])
  File "/snap/ubuntu-make/961/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/snap/ubuntu-make/961/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/snap/ubuntu-make/961/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/snap/ubuntu-make/961/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'adduser'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/ubuntu-make/961/lib/python3.8/site-packages/umake/tools.py", line 159, in wrapper
    function(*args, **kwargs)
  File "/snap/ubuntu-make/961/lib/python3.8/site-packages/umake/frameworks/baseinstaller.py", line 497, in decompress_and_install_done
    self.post_install()
  File "/snap/ubuntu-make/961/lib/python3.8/site-packages/umake/frameworks/electronics.py", line 134, in post_install
    if not f.result():
  File "/snap/ubuntu-make/961/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/snap/ubuntu-make/961/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: 'adduser'
|#####################################################################################################################################|
d@debian11:~$ which adduser
d@debian11:~$ dpkg -S bin/adduser
adduser: /usr/sbin/adduser
d@debian11:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin

d@debian11:~$ su -
Password: 
root@debian11:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
root@debian11:~# 

``` 

It seems that ubuntu-make grabs $PATH variable for normal user instead of sudoer. If it is possible, please apply some workaround into umake to prevent such unhandled exceptions while [adding user to dialout group](https://github.com/ubuntu/ubuntu-make/blob/d32e03d21abd8d8229fe8922af70aeb36b78f537/umake/frameworks/electronics.py#L48).

**Comment by LyzardKing** [comment] 2022-11-22 10:57
Does the manual  workaround fix the problem?

You can workaround by doing it manually:
sudo adduser <your_user> dialout

**Comment by N0rbert** [comment] 2022-11-22 16:46
>Does the manual workaround fix the problem?
>
>You can workaround by doing it manually:
>`sudo adduser <your_user> dialout`


Of course.
It works, but this is not user-friendly. I expect that umake works on Debian as great as on Ubuntu.

**Comment by LyzardKing** [comment] 2022-11-22 16:48
Could you open a new error with this information?
Note that I'm also changing umake to install the latest arduino versions by default (the new version 2), with the old one still available as legacy
