### ISSUE TITLE
encoding issue when downloading VSCode

### ISSUE THREAD

**Issue by geange** [ubuntu/ubuntu-make#137] opened 2015-08-13 05:42 UTC
----------------umake web visual-studio-code 
Choose installation path: --------------------/tools/web/visual-studio-code
ERROR: Download page changed its syntax or is not parsable

**Comment by didrocks** [comment] 2015-08-13 05:58
thanks for your bug report!
This is a duplicate of bug #136 which started yesterday evening with their new release.

The good news is that I just released in 14.04, 15.04 and wily Ubuntu Make 0.8 which has a fix for it! It should be published in less than half an hour, so please update to it and keep me posted!

**Comment by didrocks** [comment] 2015-08-13 05:59
(closing as duplicate)

**Comment by geange** [comment] 2015-08-13 11:33
Sorry, it couldn't work...

ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 154, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/ui/__init__.py", line 42, in display
    cls.currentUI._display(contentType)
  File "/usr/lib/python3/dist-packages/umake/ui/cli/__init__.py", line 62, in _display
    print(contentType.content)
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 74: ordinal not in range(128)

**Comment by didrocks** [comment] 2015-08-13 11:39
Oh interesting, that can be locale-related. What is your LANG settings? (env | grep LANG). I wonder if the download page is redirected to a language-specific one.

**Comment by geange** [comment] 2015-08-13 11:43
zh_CN, Chinese

**Comment by geange** [comment] 2015-08-13 11:44
LANG=zh_US
GDM_LANG=zh_CN
LANGUAGE=zh_CN:zh

**Comment by didrocks** [comment] 2015-08-13 11:48
Thanks! I'll give it a try (renaming the bug)

**Comment by geange** [comment] 2015-08-13 12:02
Thanks, I change the LANG setting, now I can use it. :100:

**Comment by didrocks** [comment] 2015-08-13 12:05
Thanks for confirming ;)

**Comment by razouckt** [comment] 2015-11-11 12:08
Encountered the same issue. Have no idea how to fix it.

**Comment by didrocks** [comment] 2015-11-12 05:55
Thanks for reviving this bug! Mind pasting you LANG settings as well if diferent from the previous one?

You can, meanwhile, try:
`LANG=C umake web visual-studio-code`
to install it

**Comment by razouckt** [comment] 2015-11-12 10:26
You says LANG settings, homeboy, I say “what ya talking 'bout?”.

**Comment by didrocks** [comment] 2015-11-12 12:07
From the command line:
$ env | grep LANG
and copy the results here :)

**Comment by razouckt** [comment] 2015-11-13 02:18
LANG=pt_BR.UTF-8
GDM_LANG=pt_BR
LANGUAGE=pt_BR:pt:en

**Comment by didrocks** [comment] 2015-11-13 08:10
Ok, it seems the issue is that you don't have your pt_BR locale fully installed, what does:
`apt-cache policy language-pack-{gnome-,}pt`
returns? If it's not installed, I recommend installing those packages with `apt install language-pack-{gnome-,}pt`
Please confirms this is what happens here ;)

I'll add a way in Ubuntu Make to fallback to C (so, plain english) for people in your situation!

**Comment by razouckt** [comment] 2015-11-13 10:22
Instalado: 1:14.04+20140410
  Candidato: 1:14.04+20140410
  Tabela de versão:
 *** 1:14.04+20140410 0
        500 http://br.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
language-pack-pt:
  Instalado: 1:14.04+20140410
  Candidato: 1:14.04+20140410
  Tabela de versão:
 *** 1:14.04+20140410 0
        500 http://br.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by didrocks** [comment] 2015-11-13 10:27
I've found and fixed some bad translations for pt_BR translations in https://github.com/ubuntu/ubuntu-make/commit/ea247a579836caad7007b110dd0975f1466ffee1. I guess this is what you are seeing here. The next Ubuntu Make release will contain the fix.

Meanwhile, try installing with:
```
export LANGUAGE=C
umake web visual-studio-code
```
and keep me posted! That should work (and fallback to english for Ubuntu Make installation).

**Comment by razouckt** [comment] 2015-11-14 11:28
The problem was resolved.
Thank you very much, Mr. Roche. Have a blessed day.

**Comment by didrocks** [comment] 2015-11-17 06:39
Excellent! closing the issue then :) Thanks for the feedback

**Closed by didrocks** 2015-11-17 06:39 UTC
Labels: bug

**Comment by razouckt** [comment] 2015-11-18 23:21
Yes.
