### ISSUE TITLE
sudo umake android studio returns dconf: Cannot spawn a message bus when setuid

### ISSUE THREAD

**Issue by yehia67** [ubuntu/ubuntu-make#456] opened 2017-06-14 13:48 UTC
after installing Android studio using this command sudo umake android android-studio it give me that error dconf-WARNING **: failed to commit changes to dconf: Cannot spawn a message bus when setuid

**Comment by LyzardKing** [comment] 2017-06-14 16:21
Please read the issue guidelines and do not type the whole issue in the title!
That said, I'd say the issue is that you're running umake with sudo.
Try running "umake android android-studio"

**Comment by yehia67** [comment] 2017-06-15 09:48
sorry i am new in open source and programming,,, i wrote the following command in the terminal to install android studio  $ sudo umake android-studio, after the installation  is done the terminal give me that error  dconf-WARNING **: failed to commit changes to dconf: Cannot spawn a message bus when setuid.

**Comment by LyzardKing** [comment] 2017-06-15 09:53
No problem, it's just that the title is really long and the body of the issue contains only the template.
Do you need to install in a system directory? If you don't you can just run without sudo (the "intended" way)

**Comment by LyzardKing** [comment] 2017-06-15 09:56
I changed the title and copied the error message in the body of the issue, if something is wrong let me know.
What version of umake are you running (run umake --version)

**Comment by yehia67** [comment] 2017-06-15 09:58
17.03

**Comment by LyzardKing** [comment] 2017-06-15 09:59
Did you try installing without sudo? or do you need android-studio to be in a system directory?

**Comment by LyzardKing** [comment] 2017-06-15 10:02
If you do you can try this, but I'm not sure it'll work: https://github.com/ubuntu/ubuntu-make/issues/79#issuecomment-86868432

umake is mainly meant to install in the user directory (without sudo)

**Comment by yehia67** [comment] 2017-06-15 10:03
i need it to be in system directory

**Comment by LyzardKing** [comment] 2017-06-15 10:07
The issue might be that it can't switch user when it needs to install the requirements...
You could try and install them manually, then try again.
The requirements are:
"openjdk-7-jdk or openjdk-8-jdk", "libncurses5:i386", "libstdc++6:i386", "zlib1g:i386"
Sorry, I'm not sure what the solution is.
If you try these let me know

**Comment by LyzardKing** [comment] 2017-06-23 07:21
@yehia67 Any updates?

**Comment by LyzardKing** [comment] 2017-10-12 22:07
Closing.
Please open if this needs further work.

**Closed by LyzardKing** 2017-10-12 22:07 UTC
