### ISSUE TITLE
Unable to download eclipse-jee

### ISSUE THREAD

**Issue by mmurari** [ubuntu/ubuntu-make#475] opened 2017-10-06 16:32 UTC
Ubuntu Version: 16.04
Tried to download eclipse-jee:
'umake ide eclipse-jee'
Getting the following error:

Downloading and installing requirements                                        |
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 140, in get_sha_and_start_download
    res = download_result[self.sha512_url]
KeyError: 'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512&r=1'

'umake --version' returns:
17.03

'umake --help' shows 'eclipse-jee' under ide command

I am new to ubuntu. Someone please help. Thanks in advance.

**Comment by LyzardKing** [comment] 2017-10-06 16:37
Please check the closed issues.
The up to date version of umake is a snap.
You have to uninstall the version of umake you have now,
then run `snap install ubuntu-make`

then you can use umake:
`ubuntu-make.umake ide eclipse-jee`

**Comment by mmurari** [comment] 2017-10-06 17:16
Thanks LyzardKing for quick reply.

I uninstalled the ubuntu-make using cmd: **sudo apt-get remove ubuntu-make**

Then tried: **snap install ubuntu-make**
but error: access denied (try with sudo)
so tried:  **sudo snap install ubuntu-make**
but again error: This revision of snap "ubuntu-make" was published using classic
       confinement and thus may perform arbitrary system changes outside of the
       security sandbox that snaps are usually confined to, which may put your
       system at risk.

       If you understand and want to proceed repeat the command including
       --classic.
Then tried:  **sudo snap install ubuntu-make --classic**
2017-10-06T22:25:11+05:30 INFO Waiting for restart...
**ubuntu-make master from 'didrocks' installed**
Finally got it installed.

--------------------------------------------------------------------

Now tried: **ubuntu-make.umake ide eclipse-jee**
But got the same error:
_ERROR: Unhandled exception
Traceback (most recent call last):
  File "/snap/ubuntu-make/75/lib/python3.5/site-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/snap/ubuntu-make/75/lib/python3.5/site-packages/umake/frameworks/ide.py", line 140, in get_sha_and_start_download
    res = download_result[self.sha512_url]
KeyError: 'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512&r=1'_

--------------------------------------------------------------------

So just checked the version again with:  **ubuntu-make.umake --version**
which returned: **17.03+snap75**

--------------------------------------------------------------------

So still having the same issue, even after snap install. Please help.

**Comment by LyzardKing** [comment] 2017-10-06 17:23
I can't replicate on my system...
It's not an issue on the eclipse page (changed or missing).
Try running `ubuntu-make.umake -vv ide eclipse-jee`

**Comment by mmurari** [comment] 2017-10-06 18:03
I tried the command.. It asked for an installation path and once I gave it, It showed the same error but started downloading with lot of debug messages. So I am not able to post the initial part of the logs here. The last part of the logs is as follows:
DEBUG: Deliver download update: {'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz&r=1': {'current': 340448784, 'size': 340448784}} of 340448784
DEBUG: Checking checksum (sha512).
DEBUG: Expected: 0288712290b74a793435bd2d1b776271badec8e98d203fc82888c2c0a52ee36b8888b11266bace1cd50eb3aa24a6bbd5302d9155246992f72454dcf4be443d29, actual: 0288712290b74a793435bd2d1b776271badec8e98d203fc82888c2c0a52ee36b8888b11266bace1cd50eb3aa24a6bbd5302d9155246992f72454dcf4be443d29.
INFO: https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz&r=1 download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz&r=1', checksum=Checksum(checksum_type=<ChecksumType.sha512: 'sha512'>, checksum_value='0288712290b74a793435bd2d1b776271badec8e98d203fc82888c2c0a52ee36b8888b11266bace1cd50eb3aa24a6bbd5302d9155246992f72454dcf4be443d29'), headers=None, ignore_encoding=False, cookies=None)] done
------------------------------------------------------------------------------------------------------------
But now when I check in the path that I had mentioned at the beginning, no file is present. I do not know where the eclipse-jee got downloaded. Please help.

**Comment by LyzardKing** [comment] 2017-10-06 18:07
Strange, because it looks like it's downloading the archive correctly. (The checksum is correct)

**Comment by mmurari** [comment] 2017-10-06 18:08
Have any guess, where I can find the downloaded eclipse?

**Comment by LyzardKing** [comment] 2017-10-06 18:11
Run the -vv command again, and stop it (with Ctrl-C) when it starts to download, so we can see what the issue is and when the error pops up

**Comment by mmurari** [comment] 2017-10-06 18:14
Here is the starting logs ...

DEBUG: No installation path provided. Requesting one.
Choose installation path: /home/murari/IT/ide/eclipse-jee
DEBUG: Installation path provided. Checking if exists.
DEBUG: Download application provider page
INFO: Start downloading DownloadItem(url='https://www.eclipse.org/downloads/eclipse-packages/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): www.eclipse.org
DEBUG: "GET /downloads/eclipse-packages/ HTTP/1.1" 200 8585
DEBUG: Deliver download update: {'https://www.eclipse.org/downloads/eclipse-packages/': {'size': 8585, 'current': 0}} of 8585
DEBUG: Deliver download update: {'https://www.eclipse.org/downloads/eclipse-packages/': {'size': 8585, 'current': 8192}} of 8585
DEBUG: Deliver download update: {'https://www.eclipse.org/downloads/eclipse-packages/': {'size': 8585, 'current': 8585}} of 8585
INFO: https://www.eclipse.org/downloads/eclipse-packages/ download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org/downloads/eclipse-packages/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None)] done
DEBUG: Parse download metadata
INFO: Start downloading DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk.tar.gz.sha512&r=1', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): www.eclipse.org
INFO: Start downloading DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512&r=1', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): www.eclipse.org
DEBUG: "GET //downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512&r=1 HTTP/1.1" 302 20
INFO: Starting new HTTP connection (1): ftp.jaist.ac.jp
DEBUG: "GET //downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk.tar.gz.sha512&r=1 HTTP/1.1" 302 20
INFO: Starting new HTTP connection (1): ftp.jaist.ac.jp
DEBUG: "GET /pub/eclipse/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512 HTTP/1.1" 200 175
DEBUG: Deliver download update: {'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512&r=1': {'size': 175, 'current': 0}} of 175
DEBUG: Deliver download update: {'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512&r=1': {'size': 175, 'current': 175}} of 175
INFO: https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512&r=1 download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512&r=1', checksum=None, headers=None, ignore_encoding=False, cookies=None)] done
DEBUG: Found download link for https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz&r=1, checksum: 0288712290b74a793435bd2d1b776271badec8e98d203fc82888c2c0a52ee36b8888b11266bace1cd50eb3aa24a6bbd5302d9155246992f72454dcf4be443d29
INFO: Installation ['openjdk-8-jdk'] pending                                                                                                                                                                |
DEBUG: Check if ['openjdk-8-jdk'] is uptodate
DEBUG: Starting ['openjdk-8-jdk'] installation
INFO: Start downloading DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz&r=1', checksum=Checksum(checksum_type=<ChecksumType.sha512: 'sha512'>, checksum_value='0288712290b74a793435bd2d1b776271badec8e98d203fc82888c2c0a52ee36b8888b11266bace1cd50eb3aa24a6bbd5302d9155246992f72454dcf4be443d29'), headers=None, ignore_encoding=False, cookies=None) to a temp file
INFO: Starting new HTTPS connection (1): www.eclipse.org
Downloading and installing requirements
DEBUG: Check if ['openjdk-8-jdk'] is uptodate
DEBUG: ['openjdk-8-jdk'] installed
DEBUG: "GET /pub/eclipse/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk.tar.gz.sha512 HTTP/1.1" 200 168
DEBUG: Deliver download update: {'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk.tar.gz.sha512&r=1': {'size': 168, 'current': 0}} of 168
DEBUG: Deliver download update: {'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk.tar.gz.sha512&r=1': {'size': 168, 'current': 168}} of 168
INFO: https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk.tar.gz.sha512&r=1 download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk.tar.gz.sha512&r=1', checksum=None, headers=None, ignore_encoding=False, cookies=None)] done
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/snap/ubuntu-make/75/lib/python3.5/site-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/snap/ubuntu-make/75/lib/python3.5/site-packages/umake/frameworks/ide.py", line 140, in get_sha_and_start_download
    res = download_result[self.sha512_url]
KeyError: 'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz.sha512&r=1'
DEBUG: "GET //downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz&r=1 HTTP/1.1" 302 20
INFO: Starting new HTTP connection (1): ftp.jaist.ac.jp
DEBUG: "GET /pub/eclipse/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz HTTP/1.1" 200 340448784
DEBUG: Deliver download update: {'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz&r=1': {'size': 340448784, 'current': 0}} of 340448784
DEBUG: Deliver download update: {'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/1/eclipse-jee-oxygen-1-linux-gtk-x86_64.tar.gz&r=1': {'size': 340448784, 'current': 8192}} of 340448784

**Comment by LyzardKing** [comment] 2017-10-06 18:24
I'm not sure what the issue here is...
I can't replicate it.

**Comment by mmurari** [comment] 2017-10-06 18:28
The logs say that the download is completed. But now the eclipse-jee is not there in the installation path that I had given at the beginning of the download and I do not know where to find it.

**Comment by mmurari** [comment] 2017-10-06 18:38
Or can the download might have happened to some other location?

**Comment by mmurari** [comment] 2017-10-07 06:59
_I just downloaded and installed using eclipse-jee using eclipse installer_. **Still I can not find the eclipse-jee downloaded by ubuntu-make. I do not know what was wrong and which path ubuntu-make took for installation. Please fix the issue, I want to download and maintain eclipse-jee using ubuntu-make.** _But for time being I am using the eclipse-jee installed through the installer. Thanks._

**Comment by mmurari** [comment] 2017-10-09 13:08
Hi. I just want to update that recently I installed firefox-dev using ubuntu-make. It is working fine and it got installed in the right installation path that I provided. so I think the eclipse-jee issue must be exclusive for the eclipse-jee package and not for other packages. Thought that this might help, so sharing. Ubuntu make is awesome. Thanks.

**Comment by LyzardKing** [comment] 2017-10-09 14:51
@mmurari , could you try and download the git version and change a line to see if it works?
in the file umake/frameworks/ide.py, change line 110 from:
`self.sha512_url = "https://www.eclipse.org/" + p.group(1) + '.sha512&r=1'`
to:
`self.sha512_url = "https://www.eclipse.org" + p.group(1) + '.sha512&r=1'`

(remove the last "/")

**Comment by mmurari** [comment] 2017-10-11 11:14
@LyzardKing , Sorry for late reply. I have already installed ubuntu-make. Please tell how to run this git version after doing the download and edit. This has been first my week with Ubuntu OS. So need your help on this or give me any link that tells me how to run it. Thanks.

**Comment by LyzardKing** [comment] 2017-10-18 15:52
Hi! Sorry for the late reply ;)
You can pull from master:
`git clone https://github.com/ubuntu/ubuntu-make.git`
then you can navigate to the file, in a file manager:
`ubuntu-make/umake/frameworks/ide.py`
and edit that file.
Then from the ubuntu-make folder, in a terminal you can run:
`bin/umake ide eclipse-jee`

Let me know if you can test this, or if you need help :)

**Comment by mmurari** [comment] 2017-10-22 14:25
Will this affect my already installed ubuntu-make? Should I remove it?

**Comment by LyzardKing** [comment] 2017-11-14 20:52
@mmurari did you try it again?
I still can't replicate the issue

**Comment by mmurari** [comment] 2017-11-19 06:06
Hi @LyzardKing. Followed your steps. But got some other error.
~/ubuntu-make$ bin/umake ide eclipse-jee
Traceback (most recent call last):
  File "bin/umake", line 27, in <module>
    from umake import main
  File "/home/murari/ubuntu-make/umake/__init__.py", line 28, in <module>
    from umake.frameworks import BaseCategory, load_frameworks
  File "/home/murari/ubuntu-make/umake/frameworks/__init__.py", line 33, in <module>
    from umake.network.requirements_handler import RequirementsHandler
  File "/home/murari/ubuntu-make/umake/network/requirements_handler.py", line 33, in <module>
    from umake.tools import Singleton, add_foreign_arch, get_foreign_archs, get_current_arch, as_root
  File "/home/murari/ubuntu-make/umake/tools.py", line 38, in <module>
    import yaml
ImportError: No module named 'yaml'

**Comment by LyzardKing** [comment] 2017-11-19 09:44
You need to install all the dependencies (like python3-yaml

On 19 Nov 2017 07:06, "mmurari" <notifications@github.com> wrote:

Hi @LyzardKing <https://github.com/lyzardking>. Followed your steps. But
got some other error.
~/ubuntu-make$ bin/umake ide eclipse-jee

Traceback (most recent call last):
File "bin/umake", line 27, in
from umake import main
File "/home/murari/ubuntu-make/umake/*init*.py", line 28, in
from umake.frameworks import BaseCategory, load_frameworks
File "/home/murari/ubuntu-make/umake/frameworks/*init*.py", line 33, in
from umake.network.requirements_handler import RequirementsHandler
File "/home/murari/ubuntu-make/umake/network/requirements_handler.py", line
33, in
from umake.tools import Singleton, add_foreign_arch, get_foreign_archs,
get_current_arch, as_root
File "/home/murari/ubuntu-make/umake/tools.py", line 38, in
import yaml
ImportError: No module named 'yaml'

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ubuntu/ubuntu-make/issues/475#issuecomment-345494672>,
or mute the thread

**Comment by LyzardKing** [comment] 2017-12-02 14:10
@mmurari, you can use the ppa now, I'm closing this issue, but open it again if the problem persists

**Closed by LyzardKing** 2017-12-02 14:10 UTC
