### ISSUE TITLE
Add Atom text editor

### ISSUE THREAD

**Issue by castrojo** [ubuntu/ubuntu-make#6] opened 2014-09-10 15:01 UTC
https://atom.io/
https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

Atom is a newer text editor, it's a great alternative to sublime and support many plugins. It's still not finished, and there is a 3rd party PPA, but this sort of fast moving project seems like a nice fit to the udtc model.

**Comment by jonobacon** [comment] 2015-11-11 00:15
I wanted to revive this old ticket. Atom is a tremendous text editor and very mature. It is completely Open Source and has a very large library of extensions. Would it be possible to package this up for Ubuntu?

**Comment by didrocks** [comment] 2015-11-13 06:25
Hey Jono,

As Atom is my editor of choice, what is used to build Ubuntu Make and something I'm using on a daily bases, I have a vest interest in getting this into Make (I'm using the .deb until now) ;)

I looked at this yesterday afternoon, and the issue is that Atom doesn't distribute an archive (tar.gz) for Linux (which enables auto-updates, doesn't require root and such), which is what is required to work with Ubuntu Make (we don't use packages to keep it available/updatable on user's directory). So, I dove into the building machinery to make this archive available, which should give the benefit later on to enable auto-update of Atom for Linux users!

The pull request is at https://github.com/atom/atom/pull/9554 and pending upstream's review :)
Then, I can jump on the Ubuntu Make side, once this is published (and the atom.io website is modified to publish the archive) to make this an available option for our users!

**Comment by LyzardKing** [comment] 2016-04-14 13:50
Since it's merged now this is another thing we can use the github api for!

**Comment by didrocks** [comment] 2016-04-14 13:52
yeah! Look at my followup coments though, they need to publish the built tarball as part of their released.

@jonobacon: getting close to it! :)

**Comment by sudopluto** [comment] 2016-06-27 22:04
It seems like atom has released 1.8.0 and they now supply tarballs.

**Closed** 2016-08-26 14:33 UTC
Labels: enhancement, help wanted, in progress
