### ISSUE TITLE
dialog missing fonts

### ISSUE THREAD

**Issue by 7ovo7** [ubuntu/ubuntu-make#593] opened 2019-02-18 02:17 UTC
I write from Arch and the dialog missing all fonts and show a squared blocks instead.
![lighttable_missing-fonts](https://user-images.githubusercontent.com/46967291/52924142-ab2d6500-332b-11e9-84cb-dd3ea85cf8f3.png)

**Comment by LyzardKing** [comment] 2019-02-18 10:53
Duplicate of #573

**Closed by LyzardKing** 2019-02-18 10:53 UTC
