### ISSUE TITLE
Error installing eclipse-javascript [Connection timed out]

### ISSUE THREAD

**Issue by raveesh-me** [ubuntu/ubuntu-make#539] opened 2018-04-21 07:36 UTC
Make sure you try the following before submitting the issue, thank you!

- Check that umake is the latest version (https://github.com/ubuntu/ubuntu-make/releases)
yes, it is.
`17.03`

- If you're not running the latest development version of Ubuntu, or a flavor based on it, add the ppa as described in the README.
`Ubuntu 18.04 Beta 2`

Maybe the bug is fixed in the master branch? If you have all dependencies installed, you can run `umake` easily from it:

No give. It didn't work

```
$ git clone https://github.com/ubuntu/ubuntu-make
$ cd ubuntu-make
$ bin/umake <your-command>
```

If all this doesn't solve the problem you're having, please submit the issue including the version of ubuntu and umake itself.

Ubuntu Version 18.04 Beta 2
Umake version 17.03
Error:
```
ERROR: https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz.sha512&r=1 couldn't finish download: HTTPConnectionPool(host='ftp.kaist.ac.kr', port=80): Max retries exceeded with url: /eclipse/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz.sha512 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2bc0714a8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 129, in get_sha_and_start_download
    sha512 = res.buffer.getvalue().decode('utf-8').split()[0]
AttributeError: 'NoneType' object has no attribute 'getvalue'

```

**Comment by LyzardKing** [comment] 2018-04-21 07:41
Could there have been an issue with your internet connection?
I'm not sure what other reason it might have to time out...
I tested it and both the ppa and the git repo work for me...

**Comment by raveesh-me** [comment] 2018-04-21 08:11
```
INFO: Logging level set to DEBUG
DEBUG: New framework module: umake.frameworks.android
DEBUG: Found category: AndroidCategory
INFO: Create a new apt cache
DEBUG: Check if ['clang'] is installed
INFO: clang isn't installed
DEBUG: Opening /home/raveesh/.config/umake
DEBUG: Attach framework AndroidNDK to Android
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk', 'libncurses5:i386', 'libstdc++6:i386', 'zlib1g:i386'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework AndroidSDK to Android
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk', 'libncurses5:i386', 'libstdc++6:i386', 'zlib1g:i386'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Check if ['libncurses5:i386', 'libstdc++6:i386', 'zlib1g:i386', 'openjdk-8-jdk'] is installed
DEBUG: Attach framework AndroidStudio to Android
DEBUG: Check if [] is installed
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
DEBUG: Attach framework EclipseADTForRemoval to Android
DEBUG: New framework module: umake.frameworks.baseinstaller
DEBUG: New framework module: umake.frameworks.crystal
DEBUG: Found category: CrystalCategory
DEBUG: Check if ['libbsd-dev', 'libedit-dev', 'libevent-dev', 'libevent-core-2.0-5 | libevent-core-2.1-6', 'libevent-extra-2.0-5 | libevent-extra-2.1-6', 'libevent-openssl-2.0-5 | libevent-openssl-2.1-6', 'libevent-pthreads-2.0-5 | libevent-pthreads-2.1-6', 'libgmp-dev', 'libgmpxx4ldbl', 'libssl-dev', 'libxml2-dev', 'libyaml-dev', 'libreadline-dev', 'automake', 'libtool', 'llvm', 'libpcre3-dev', 'build-essential', 'libgc-dev'] is installed
INFO: libbsd-dev isn't installed
INFO: libedit-dev isn't installed
INFO: libevent-dev isn't installed
DEBUG: Check if ['libevent-core-2.0-5'] is installed
INFO: libevent-core-2.0-5 isn't installed
DEBUG: Check if ['libevent-core-2.1-6'] is installed
INFO: libevent-core-2.1-6 isn't installed
INFO: libevent-core-2.0-5 | libevent-core-2.1-6 isn't installed
DEBUG: Check if ['libevent-extra-2.0-5'] is installed
INFO: libevent-extra-2.0-5 isn't installed
DEBUG: Check if ['libevent-extra-2.1-6'] is installed
INFO: libevent-extra-2.1-6 isn't installed
INFO: libevent-extra-2.0-5 | libevent-extra-2.1-6 isn't installed
DEBUG: Check if ['libevent-openssl-2.0-5'] is installed
INFO: libevent-openssl-2.0-5 isn't installed
DEBUG: Check if ['libevent-openssl-2.1-6'] is installed
INFO: libevent-openssl-2.1-6 isn't installed
INFO: libevent-openssl-2.0-5 | libevent-openssl-2.1-6 isn't installed
DEBUG: Check if ['libevent-pthreads-2.0-5'] is installed
INFO: libevent-pthreads-2.0-5 isn't installed
DEBUG: Check if ['libevent-pthreads-2.1-6'] is installed
INFO: libevent-pthreads-2.1-6 isn't installed
INFO: libevent-pthreads-2.0-5 | libevent-pthreads-2.1-6 isn't installed
INFO: libgmp-dev isn't installed
INFO: libgmpxx4ldbl isn't installed
INFO: libssl-dev isn't installed
INFO: libxml2-dev isn't installed
INFO: libyaml-dev isn't installed
INFO: automake isn't installed
INFO: libtool isn't installed
INFO: llvm isn't installed
INFO: libpcre3-dev isn't installed
INFO: libgc-dev isn't installed
INFO: libevent-core-2.0-5 isn't available on this platform
INFO: libevent-openssl-2.0-5 isn't available on this platform
DEBUG: Attach framework CrystalLang to Crystal
DEBUG: New framework module: umake.frameworks.dart
DEBUG: Found category: DartCategory
DEBUG: Check if [] is installed
DEBUG: Check if [] is installed
DEBUG: Dart SDK is installed
DEBUG: Attach framework DartLang to Dart
DEBUG: Check if [] is installed
INFO: Don't register Dart Editor as it's not installable on this configuration.
DEBUG: Attach framework DartLangEditorRemoval to Dart
DEBUG: New framework module: umake.frameworks.electronics
DEBUG: Found category: ElectronicsCategory
DEBUG: Attach framework Arduino to Electronics
DEBUG: Check if [] is installed
DEBUG: Attach framework Eagle to Electronics
DEBUG: New framework module: umake.frameworks.games
DEBUG: Found category: GamesCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework Blender to Games
DEBUG: Check if ['libxtst6:i386', 'libxext6:i386', 'libxi6:i386', 'libncurses5:i386', 'libxt6:i386', 'libxpm4:i386', 'libxmu6:i386', 'libgtk2.0-0:i386', 'libatk1.0-0:i386', 'libc6:i386', 'libcairo2:i386', 'libexpat1:i386', 'libfontconfig1:i386', 'libfreetype6:i386', 'libglib2.0-0:i386', 'libice6:i386', 'libpango1.0-0:i386', 'libpng12-0:i386', 'libsm6:i386', 'libxau6:i386', 'libxcursor1:i386', 'libxdmcp6:i386', 'libxfixes3:i386', 'libx11-6:i386', 'libxinerama1:i386', 'libxrandr2:i386', 'libxrender1:i386', 'zlib1g:i386', 'libnss3-1d:i386', 'libnspr4-0d:i386', 'libcurl3:i386', 'libasound2:i386'] is installed
INFO: libxtst6:i386 isn't installed
INFO: libxext6:i386 isn't installed
INFO: libxi6:i386 isn't installed
INFO: libxt6:i386 isn't installed
INFO: libxpm4:i386 isn't installed
INFO: libxmu6:i386 isn't installed
INFO: libgtk2.0-0:i386 isn't installed
INFO: libatk1.0-0:i386 isn't installed
INFO: libcairo2:i386 isn't installed
INFO: libexpat1:i386 isn't installed
INFO: libfontconfig1:i386 isn't installed
INFO: libfreetype6:i386 isn't installed
INFO: libglib2.0-0:i386 isn't installed
INFO: libice6:i386 isn't installed
INFO: libpango1.0-0:i386 isn't installed
INFO: libpng12-0:i386 isn't installed
INFO: libsm6:i386 isn't installed
INFO: libxau6:i386 isn't installed
INFO: libxcursor1:i386 isn't installed
INFO: libxdmcp6:i386 isn't installed
INFO: libxfixes3:i386 isn't installed
INFO: libx11-6:i386 isn't installed
INFO: libxinerama1:i386 isn't installed
INFO: libxrandr2:i386 isn't installed
INFO: libxrender1:i386 isn't installed
INFO: libnss3-1d:i386 isn't installed
INFO: libnspr4-0d:i386 isn't installed
INFO: libcurl3:i386 isn't installed
INFO: libasound2:i386 isn't installed
INFO: libpng12-0:i386 isn't available on this platform
INFO: libnss3-1d:i386 isn't available on this platform
INFO: libnspr4-0d:i386 isn't available on this platform
INFO: Don't register Stencyl as it's not installable on this configuration.
DEBUG: Attach framework Stencyl to Games
DEBUG: Check if [] is installed
DEBUG: Attach framework Superpowers to Games
DEBUG: Check if [] is installed
DEBUG: Attach framework Twine to Games
DEBUG: Check if [] is installed
INFO: Don't register Unity3D as it's not installable on this configuration.
DEBUG: Attach framework Unity3D to Games
DEBUG: New framework module: umake.frameworks.go
DEBUG: Found category: GoCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework GoLang to Go
DEBUG: New framework module: umake.frameworks.ide
DEBUG: Found category: IdeCategory
DEBUG: Attach framework Arduino to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework Atom to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework BaseNetBeans to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework CLion to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework DataGrip to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework EclipseCPP to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework EclipseJEE to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework EclipseJS to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework EclipseJava to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework EclipsePHP to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework GogLand to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework Idea to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework IdeaUltimate to IDE
DEBUG: Check if [] is installed
DEBUG: Check if [] is installed
DEBUG: Attach framework LightTable to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework PhpStorm to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework Processing to IDE
DEBUG: Check if ['python', 'python3'] is installed
DEBUG: Attach framework PyCharm to IDE
DEBUG: Check if ['python', 'python3'] is installed
DEBUG: Attach framework PyCharmEducational to IDE
DEBUG: Check if ['python', 'python3'] is installed
DEBUG: Attach framework PyCharmProfessional to IDE
DEBUG: Check if ['mono-devel'] is installed
INFO: mono-devel isn't installed
DEBUG: Attach framework Rider to IDE
DEBUG: Check if ['ruby'] is installed
INFO: ruby isn't installed
DEBUG: Attach framework RubyMine to IDE
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework SpringToolsSuite to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework SublimeText to IDE
DEBUG: Check if ['libgtk2.0-0', 'libgconf-2-4'] is installed
DEBUG: Check if ['libgtk2.0-0', 'libgconf-2-4'] is installed
DEBUG: Attach framework VisualStudioCode to IDE
DEBUG: Check if [] is installed
DEBUG: Attach framework WebStorm to IDE
DEBUG: New framework module: umake.frameworks.kotlin
DEBUG: Found category: KotlinCategory
DEBUG: Check if ['openjdk-7-jre | openjdk-8-jre'] is installed
DEBUG: Check if ['openjdk-7-jre'] is installed
INFO: openjdk-7-jre isn't installed
DEBUG: Check if ['openjdk-8-jre'] is installed
DEBUG: Check if ['openjdk-8-jre'] is installed
DEBUG: Kotlin Lang is installed
DEBUG: Attach framework KotlinLang to Kotlin
DEBUG: New framework module: umake.frameworks.maven
DEBUG: Found category: MavenCategory
DEBUG: Check if ['openjdk-7-jdk | openjdk-8-jdk'] is installed
DEBUG: Check if ['openjdk-7-jdk'] is installed
INFO: openjdk-7-jdk isn't installed
DEBUG: Check if ['openjdk-8-jdk'] is installed
DEBUG: Attach framework MavenLang to Maven
DEBUG: New framework module: umake.frameworks.nodejs
DEBUG: Found category: NodejsCategory
DEBUG: Check if [] is installed
DEBUG: Check if [] is installed
DEBUG: Nodejs Lang is installed
DEBUG: Attach framework NodejsLang to Nodejs
DEBUG: New framework module: umake.frameworks.rust
DEBUG: Found category: RustCategory
DEBUG: Check if [] is installed
DEBUG: Attach framework RustLang to Rust
DEBUG: New framework module: umake.frameworks.scala
DEBUG: Found category: ScalaCategory
DEBUG: Check if ['openjdk-7-jre | openjdk-8-jre'] is installed
DEBUG: Check if ['openjdk-7-jre'] is installed
INFO: openjdk-7-jre isn't installed
DEBUG: Check if ['openjdk-8-jre'] is installed
DEBUG: Attach framework ScalaLang to Scala
DEBUG: New framework module: umake.frameworks.swift
DEBUG: Found category: SwiftCategory
DEBUG: Check if ['clang', 'libicu-dev'] is installed
INFO: clang isn't installed
INFO: libicu-dev isn't installed
DEBUG: Attach framework SwiftLang to Swift
DEBUG: New framework module: umake.frameworks.web
DEBUG: Found category: WebCategory
DEBUG: Check if [] is installed
DEBUG: Check if [] is installed
DEBUG: Attach framework FirefoxDev to Web
DEBUG: Check if [] is installed
DEBUG: Attach framework PhantomJS to Web
DEBUG: Skipping main having no framework
DEBUG: Call run_for on Eclipse JavaScript
DEBUG: No installation path provided. Requesting one.
Choose installation path: /home/raveesh/.local/share/umake/ide/eclipse-javascript
DEBUG: Installation path provided. Checking if exists.
DEBUG: Download application provider page
INFO: Start downloading DownloadItem(url='https://www.eclipse.org/downloads/eclipse-packages/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None) in memory
DEBUG: Starting new HTTPS connection (1): www.eclipse.org
DEBUG: https://www.eclipse.org:443 "GET /downloads/eclipse-packages/ HTTP/1.1" 200 10091
DEBUG: Deliver download update: {'https://www.eclipse.org/downloads/eclipse-packages/': {'current': 0, 'size': 10091}} of 10091
DEBUG: Deliver download update: {'https://www.eclipse.org/downloads/eclipse-packages/': {'current': 8192, 'size': 10091}} of 10091
DEBUG: Deliver download update: {'https://www.eclipse.org/downloads/eclipse-packages/': {'current': 10091, 'size': 10091}} of 10091
INFO: https://www.eclipse.org/downloads/eclipse-packages/ download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org/downloads/eclipse-packages/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None)] done
DEBUG: Parse download metadata
INFO: Start downloading DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz.sha512&r=1', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
DEBUG: Starting new HTTPS connection (1): www.eclipse.org
DEBUG: https://www.eclipse.org:443 "GET //downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz.sha512&r=1 HTTP/1.1" 302 0
DEBUG: Starting new HTTP connection (1): download.eclipse.org
DEBUG: http://download.eclipse.org:80 "GET /technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz.sha512 HTTP/1.1" 200 183
DEBUG: Deliver download update: {'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz.sha512&r=1': {'current': 0, 'size': 183}} of 183
DEBUG: Deliver download update: {'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz.sha512&r=1': {'current': 183, 'size': 183}} of 183
INFO: https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz.sha512&r=1 download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz.sha512&r=1', checksum=None, headers=None, ignore_encoding=False, cookies=None)] done
DEBUG: Found download link for https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz&r=1, checksum: 57ded613c42391bda64d809e4ba47c6cb6e1b47957f51a9b64a1576c00c977064d79f1d7f08cda2ebac9d195bf6302f3c8048f8afb46b8567c4d28dcc1eed204
INFO: Installation ['openjdk-8-jdk'] pending                                   |
DEBUG: Check if ['openjdk-8-jdk'] is uptodate
DEBUG: Starting ['openjdk-8-jdk'] installation
INFO: Start downloading DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz&r=1', checksum=Checksum(checksum_type=<ChecksumType.sha512: 'sha512'>, checksum_value='57ded613c42391bda64d809e4ba47c6cb6e1b47957f51a9b64a1576c00c977064d79f1d7f08cda2ebac9d195bf6302f3c8048f8afb46b8567c4d28dcc1eed204'), headers=None, ignore_encoding=False, cookies=None) to a temp file
DEBUG: Check if ['openjdk-8-jdk'] is uptodate
Downloading and installing requirements
DEBUG: Starting new HTTPS connection (1): www.eclipse.org
DEBUG: ['openjdk-8-jdk'] installed
DEBUG: https://www.eclipse.org:443 "GET //downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz&r=1 HTTP/1.1" 302 0
DEBUG: Starting new HTTP connection (1): ftp.kaist.ac.kr
ERROR: https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz&r=1 couldn't finish download: HTTPConnectionPool(host='ftp.kaist.ac.kr', port=80): Max retries exceeded with url: /eclipse/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf64acd6a0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz&r=1', checksum=Checksum(checksum_type=<ChecksumType.sha512: 'sha512'>, checksum_value='57ded613c42391bda64d809e4ba47c6cb6e1b47957f51a9b64a1576c00c977064d79f1d7f08cda2ebac9d195bf6302f3c8048f8afb46b8567c4d28dcc1eed204'), headers=None, ignore_encoding=False, cookies=None)] done
100% |#########################################################################|
ERROR: HTTPConnectionPool(host='ftp.kaist.ac.kr', port=80): Max retries exceeded with url: /eclipse/technology/epp/downloads/release/oxygen/3a/eclipse-javascript-oxygen-3a-linux-gtk-x86_64.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf64acd6a0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
DEBUG: Starting new HTTPS connection (1): github.com
DEBUG: https://github.com:443 "GET /ubuntu/ubuntu-make/releases HTTP/1.1" 200 None
```

Here is the output.
eclipse-cpp installed without any hiccups. The issue is network related, but I don't think the issue is within my PC for all other packages install easily.

**Comment by LyzardKing** [comment] 2018-09-21 06:16
@raveesh-me 
Is it working now? or do you still get the same issue?

**Comment by LyzardKing** [comment] 2018-09-24 08:45
Closing since it should be fixed. If the problem is still present we'll open the issue and figure it out.

**Closed by LyzardKing** 2018-09-24 08:45 UTC
