### ISSUE TITLE
Latest version of umake has issues with Ubuntu 14.04

### ISSUE THREAD

**Issue by kiklop74** [ubuntu/ubuntu-make#351] opened 2016-09-24 09:33 UTC
The other day I tried to update umake (16.09) using official PPA for Ubuntu 14.04. Got this error:

```bash
Setting up ubuntu-make (16.09~trusty1) ...
/var/lib/dpkg/info/ubuntu-make.postinst: 6: /var/lib/dpkg/info/ubuntu-make.postinst: register-python-argcomplete3: not found
dpkg: error processing package ubuntu-make (--configure):
 subprocess installed post-installation script returned error exit status 127
```
register-python-argcomplete3 is available in Ubuntu 16.04+ only

**Comment by didrocks** [comment] 2016-09-26 04:58
Hi,

We were already using python-argcomplete3 for a long time in 14.04, we have a dedicated ppa for it.

Do you mind looking which version of python-arcomplete3 you have installed, if you have an incompatible version from another ppa as seen in issue #350?

**Comment by kiklop74** [comment] 2016-09-26 10:21
It is the same issue as #350 . I often install postgres from their official repo. How do I force it not to install this package?

**Comment by kiklop74** [comment] 2016-09-26 10:40
This process seems to be working:
Install umake prior to installing postgres repo
sudo apt-mark hold python3-argcomplete
Install pg repo
But it is quite inconvenient. If somebody does the wrong order of setup any umake update will have this error message...

**Comment by didrocks** [comment] 2016-09-28 07:33
Indeed, I need to take some time to update to latest python3-argcomplete, hoping they are still shipping that registration script.

For now, I'm closing this bug report as it's a duplicate of #350 and related to another ppa. Happy that it's fixed for you! :)

**Closed by didrocks** 2016-09-28 07:33 UTC
