### ISSUE TITLE
android category only shows ndk, no sdk.On 16.04

### ISSUE THREAD

**Issue by phalbert** [ubuntu/ubuntu-make#307] opened 2016-05-06 01:08 UTC
![screenshot from 2016-05-06 07-06-27](https://cloud.githubusercontent.com/assets/8656262/15061629/36f1cb26-1340-11e6-9d57-c1892e2415fc.png)

**Comment by phalbert** [comment] 2016-05-06 01:09
![screenshot from 2016-05-06 07-07-33](https://cloud.githubusercontent.com/assets/8656262/15061643/58763b92-1340-11e6-984f-699b0787d75a.png)

**Comment by LyzardKing** [comment] 2016-05-06 06:10
Did you add the ppa? You need the latest version on 16.04.
The correct umake version is 16.05

**Comment by swidmer** [comment] 2016-05-06 23:08
I can confirm this issue on ubuntu 16.04

this is what i get with umake -v:

 umake -v
INFO: Logging level set to INFO
INFO: Create a new apt cache
INFO: No configuration file found
INFO: openjdk-7-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Android SDK as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Android Studio as it's not installable on this configuration.
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
INFO: Don't register Dart Editor as it's not installable on this configuration.
INFO: libxtst6:i386 isn't installed
INFO: libxext6:i386 isn't installed
INFO: libxi6:i386 isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libxt6:i386 isn't installed
INFO: libxpm4:i386 isn't installed
INFO: libxmu6:i386 isn't installed
INFO: libgtk2.0-0:i386 isn't installed
INFO: libatk1.0-0:i386 isn't installed
INFO: libc6:i386 isn't installed
INFO: libcairo2:i386 isn't installed
INFO: libexpat1:i386 isn't installed
INFO: libfontconfig1:i386 isn't installed
INFO: libfreetype6:i386 isn't installed
INFO: libglib2.0-0:i386 isn't installed
INFO: libice6:i386 isn't installed
INFO: libpango1.0-0:i386 isn't installed
INFO: libpng12-0:i386 isn't installed
INFO: libsm6:i386 isn't installed
INFO: libxau6:i386 isn't installed
INFO: libxcursor1:i386 isn't installed
INFO: libxdmcp6:i386 isn't installed
INFO: libxfixes3:i386 isn't installed
INFO: libx11-6:i386 isn't installed
INFO: libxinerama1:i386 isn't installed
INFO: libxrandr2:i386 isn't installed
INFO: libxrender1:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: libnss3-1d:i386 isn't installed
INFO: libnspr4-0d:i386 isn't installed
INFO: libcurl3:i386 isn't installed
INFO: libasound2:i386 isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Arduino as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Netbeans as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register CLion as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register DataGrip as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Eclipse CPP as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Eclipse as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Eclipse PHP as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Idea as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Idea Ultimate as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register PhpStorm as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register PyCharm as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register PyCharm Educational as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register PyCharm Professional as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register RubyMine as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Spring Tools Suite as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register WebStorm as it's not installable on this configuration.
INFO: clang isn't installed
INFO: libicu-dev isn't installed
usage: umake [--help] [-v] [-r] [--version]
             {games,scala,rust,go,swift,nodejs,web,dart,ide,android} ...

Deploy and setup developers environment easily on ubuntu

positional arguments:
  {games,scala,rust,go,swift,nodejs,web,dart,ide,android}
                        Developer environment
    games               Games Development Environment
    scala               The Scala Programming Language
    rust                Rust language
    go                  Go language
    swift               Swift language
    nodejs              Nodejs stable
    web                 Web Developer Environment
    dart                Dartlang Development Environment
    ide                 Generic IDEs
    android             Android Development Environment

optional arguments:
  --help                Show this help
  -v, --verbose         Increase output verbosity (2 levels)
  -r, --remove          Remove specified framework if installed
  --version             Print version and exit

Note that you can also configure different debug logging behavior using
LOG_CFG that points to a log yaml profile.

**Comment by swidmer** [comment] 2016-05-06 23:10
I also receive  this error when trying to install android-ndk, android studio is not even available...

ERROR: http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip couldn't finish download: The checksum of http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip doesn't match. Corrupted download? Aborting.
100% |#########################################################################|
ERROR: The checksum of http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip doesn't match. Corrupted download? Aborting.

**Comment by swidmer** [comment] 2016-05-06 23:39
I understand LyzardKing's answer now.

you need to not install umake from the standard ubuntu repositories, instead add to your repository the following from the command line (terminal):

sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make

the run: sudo apt-get update
and then run: sudo apt-get upgrade
assuming you installed the version from the regular ubuntu repositories.

if this is a new install the run your:
sudo apt-get install ubuntu-make

Have fun!!  Note this is a work around to the issue with the standard ubuntu-make in the regular repositories, and puts you on the channel with the latest releases from the umake  team.

**Comment by Heinerion** [comment] 2016-05-12 20:04
Thank you @swidmer, saved my day :+1:

**Comment by Ammly** [comment] 2016-05-13 11:40
Thank you @swidmer. This solved my problem too.

**Comment by mbtamuli** [comment] 2016-05-20 00:43
Thank you @swidmer. This solved the issue.

But just to point out something.

> If you are on the latest Ubuntu version (at the time of writing, it is 16.04, codename Xenial), you can install it directly from the Universe archive:
>
>$ sudo apt install ubuntu-make

**Comment by didrocks** [comment] 2016-05-20 07:17
Note that "latest version" infered "latest development version", so yakkety right now, but yeah, this should be rephrased :)

**Comment by swidmer** [comment] 2016-05-20 17:18
mbtamuli, 

If ubuntu-make in the 16.04 LTS worked correctly, without adding the development channel, there would have been no need for these posts.

Therefore the bug is still verified, and with luck the development team will release their current compliation to the release channel.

Happy Coding and Testing :)

**Comment by Michael21011** [comment] 2016-11-05 07:21
Problem still exists. Only the way by swidmer is working for me today.

**Comment by LyzardKing** [comment] 2017-03-07 08:00
As the readme says the recommended way to install Ubuntu make is to add the ppa.
Closing since the original issue has been solved

**Closed by LyzardKing** 2017-03-07 08:00 UTC
