### ISSUE TITLE
Firefox Dev: Download page changed its syntax or is not parsable

### ISSUE THREAD

**Issue by fabioqcorreia** [ubuntu/ubuntu-make#423] opened 2017-03-08 00:09 UTC
sudo umake web firefox-dev
Choose installation path: /home/fabio/.local/share/umake/web/firefox-dev
ERROR: Download page changed its syntax or is not parsable

**Comment by LyzardKing** [comment] 2017-03-08 07:43
What version of ubuntu-make are you using? The latest is 16.11.1.

**Comment by LyzardKing** [comment] 2017-03-08 11:40
The latest version works. If you don't have 16.11.1 you have to add the PPA, as described in the README.
Closing for now, but please reopen if the issue is not solved

**Closed by LyzardKing** 2017-03-08 11:40 UTC

**Comment by fabioqcorreia** [comment] 2017-03-10 01:19
@LyzardKing, sorry for the delay.

I am using Linux Mint 18.1 (16.04 LTS / Xenial), it seems I can't upgrade higher than 16.02.01, maybe a kernel upgrade would solve it?

**Comment by fabioqcorreia** [comment] 2017-03-10 01:40
Fixed it adding properly the PPA. Thanks!
