### ISSUE TITLE
Invalid choice error is confusing for valid targets not existing on the arch in use

### ISSUE THREAD

**Issue by seb128** [Ubuntu/ubuntu-make#100] opened 2015-05-04 16:35 UTC
The umake 0.7 blog mention to download the current version and try "umake web visual-studio-code", on i386 that returns an error saying that "visual-studio-code" is invalid. That's true but the blog post didn't specify that the product is amd64 specific ... it would be a nice touch if when trying to install a valid product not existing for your architecture the error would state "only available on amd64" for example (that would explain what the issue rather than having the user wondering if he got the right version/did something wrong)

**Comment by didrocks** [comment] 2015-05-05 06:13
Thanks for the bug report. Indeed, that wasn't mentioned explicitely in the blog post. However, it's explicitely marked as available on amd64 on the framework, hence the error message about invalid choice.

However, giving an exact reason is more tricky than simply the arch restriction. The cause could be the arch, it can be as well that some packages are not available in the apt repository at the moment, it can be the ubuntu version as well. I wonder how that can be dealt in an interesting way, because:
1. I don't want those options to be shown in bash completion as they are not installable (this is already working well nowdays, even for uninstalling newly unsupported frameworks, they are only shown for --remove only if they are installed, but are not reinstallable)
2. we should make it clear they can't be installed

Maybe just printing them in --help with a "Not installable on that machine" would be sufficient, wdyt?

**Comment by seb128** [comment] 2015-05-05 06:44
"Not installable on that machine" would be better since it would remove the question "did I do anything wrong" or "is the correct version installed", it wouldn't help the user much on figuring out what is needed to be able to install it though (in this case "get a modern 64 bits system") ... so I think that would be an improvement even if not a perfect solution

**Comment by LyzardKing** [comment] 2017-12-29 08:17
This information is now available in the --list commands. Closing.

**Closed by LyzardKing** 2017-12-29 08:17 UTC
Labels: enhancement
