### ISSUE TITLE
ERROR: [Errno 8] Exec format error when installing PyCharm Educational on Ubuntu 15.04.

### ISSUE THREAD

**Issue by thhgcn** [ubuntu/ubuntu-make#153] opened 2015-09-24 16:48 UTC
This is what I got when I was trying to install PyCharm Educational on Ubuntu 15.04:

~$: umake ide pycharm-educational
Choose installation path: /home/$USER/tools/ide/pycharm-educational
Downloading and installing requirements                                       |
100% |########################################################################|
Installing PyCharm Educational
ERROR: A decompression to /home/$USER/tools/ide/pycharm-educational failed: [Errno 8] Exec format error
Traceback (most recent call last):
  File "/usr/lib/python3.4/tarfile.py", line 180, in nti
    n = int(nts(s, "ascii", "strict") or "0", 8)
  File "/usr/lib/python3.4/tarfile.py", line 164, in nts
    return s.decode(encoding, errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd9 in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/tarfile.py", line 2249, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.4/tarfile.py", line 1083, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.4/tarfile.py", line 1025, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/lib/python3.4/tarfile.py", line 182, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/decompressor.py", line 91, in _decompress
    archive = tarfile.open(fileobj=fd, mode='r|*')
  File "/usr/lib/python3.4/tarfile.py", line 1578, in open
    t = cls(name, filemode, stream, **kwargs)
  File "/usr/lib/python3.4/tarfile.py", line 1470, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.4/tarfile.py", line 2261, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/decompressor.py", line 94, in _decompress
    archive = self.ZipFileWithPerm(fd.name)
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/umake/decompressor.py", line 105, in _decompress
    archive = subprocess.Popen([name, "-o{}".format(dest)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
ERROR: [Errno 8] Exec format error

**Edit:** this happens using both regular user and sudo

**Comment by didrocks** [comment] 2015-09-25 06:31
Thanks for reporting this bug and help to make Ubuntu Make better!
Oh indeed, I'm seeing that as well in the tests. I won't have the time to get to that before before (seems like encoding should be passed to tarfile). If anybody beat me to it, please feel free, otherwise, will work on it on Monday!

Sorry for the inconvenience, thanks again for your feedback!

**Comment by thhgcn** [comment] 2015-09-28 01:42
And thank you for your rapid reply. I'm not a coder, so I really sorry for not help more. But I'm here for anything else.

**Comment by didrocks** [comment] 2015-09-28 13:33
Ok, it should be now fixed in trunk! (I'll cut a release in the ubuntu make desktop ppa tomorrow).

For the record, the issue is that now the link, despite ?os=linux is returning a windows binary. They changed the linux binary path on their website to pycharm-edu instead of pycharm-educational.

If you want to try before the next release, you can git clone the repo, cd into it and just change "umake" command line by "bin/umake" and that should work :)

Thanks again for reporting this bug!

**Closed by didrocks** 2015-09-28 13:33 UTC
Labels: bug
