### ISSUE TITLE
How to update installed software?

### ISSUE THREAD

**Issue by thagabe** [ubuntu/ubuntu-make#122] opened 2015-07-04 08:28 UTC
I would like to know how to the packages installed are updated. For example go, eclipse, visual studio. Does umake have some sort of update function since go is a terminal command tool so it doesn't check if there is a new version. Unlike android studio that has an update functionality. 

Thank You!

**Comment by Tinche** [comment] 2015-07-04 13:28
We've thought about it (https://github.com/ubuntu/ubuntu-make/issues/74) but there's nothing specific yet.

You can manually update by removing the tool using --remove and installing it again, this should keep your config and fetch the latest version.

**Comment by Kuzirashi** [comment] 2015-07-09 09:29
:+1: +1

**Comment by didrocks** [comment] 2015-07-16 22:44
Thanks for the suggestion!

As Tinche told, we started the discussion on #74. I would really be in favor in adding this remove/readd (but maybe a little bit smarter, like keeping some of the known profiles directory and updating existing launcher for instance instead of wiping it and readding to the end?) for frameworks which don't have their own update mechanism built-in. Then, what should be the command line, and which what framework to start? (I guess, go should be one of the first).

I'm happy to continue this discussion on bug #74 maybe and duplicate this one there?
Duplicate of #74

**Closed by didrocks** 2015-07-16 22:44 UTC
