### ISSUE TITLE
Add Rust support

### ISSUE THREAD

**Issue by mhalano** [ubuntu/ubuntu-make#104] opened 2015-05-12 20:55 UTC
Rust is a new language. The support can be installed using the command:
curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly
And there is available the SolidOak (https://sekao.net/solidoak/) a IDE for Rust.

**Comment by Tinche** [comment] 2015-08-21 22:36
I'll take this.

**Comment by didrocks** [comment] 2015-08-24 12:52
@Tinche: thanks for looking into this! Just a word on warning here: I'm varying about running a .sh script rather than unpacking which would be the preferred method (running scripts like that during an installation from things not coming from the archive can violate the ubuntu policy). Do you think we can find a prepared tar that can be just unpack?

**Comment by Tinche** [comment] 2015-08-27 07:35
There are archives here: https://www.rust-lang.org/install.html, I have this implemented. The problem is, the archives themselves contain an install script, so I'm not sure what exactly to do about this.

As far as I can tell, we actually need to change the global system state (i.e. root access) for the toolchain to work as intended. There are libraries that need to be in a specific place, and ld.conf.d is global-only right?

**Comment by didrocks** [comment] 2015-08-27 07:42
For the script, if this is the same kind of installer than unity3D (meaning a script including the archive file itself), we have some support in Ubuntu Make to easily deal with that case. Just look at my Unity 3D branch once it's up.

On the toolchain, argh on changing the global system state. Yeah, ld.conf.d is global. Any way we can get things done thanks to a wrapper using LD_LIBRARY_PATH or such?

**Comment by jravetch** [comment] 2015-11-02 18:42
@didrocks @Tinche  Any update on getting rust working with umake?  Would love to see this working.

**Comment by Tinche** [comment] 2015-11-02 23:03
I've pushed what I have (which is web page parsing and downloading) to https://github.com/Tinche/ubuntu-make/commit/6fd3b27cea08132576f4a883c62b1d9e44dd6220, if it's any help.

Note that I haven't looked at this since the original comments, so the web page might have changed in the mean time.

**Comment by jravetch** [comment] 2015-11-03 02:32
@Tinche Cool thanks.  I've made a few changes to support the updated download page and add env variables.  See https://github.com/jravetch/ubuntu-make/commit/0954ce93190749cd3cac69401032c8d030300277 It works with those patches. 

@didrocks Having a weird issue with add_env_to_user, where I need to set two PATH variables, one for rustc, the other for cargo.  However, only cargo is getting set.

**Comment by didrocks** [comment] 2015-11-03 07:55
@Tinche: thanks for your initial work! It goes a long way ;)

@jravetch: answering you on the PR directly.

**Comment by jravetch** [comment] 2015-11-11 01:12
@didrocks Thanks for your help getting the Rust framework part of ubuntu make.  I think we can safely close this issue now.

**Comment by mhalano** [comment] 2015-11-11 01:59
Hello everybody!

Glad to know my feature request became reality! Is always good when people listen to us to the greater good. I'm not a Rust developer, I just thought Rust could be useful for others. Glad you agree with me. :)

**Comment by didrocks** [comment] 2015-11-18 09:31
Closing the bug now that it's in master :)

**Closed by didrocks** 2015-11-18 09:31 UTC
Labels: help wanted
