### ISSUE TITLE
[Question] Product update

### ISSUE THREAD

**Issue by rosolko** [ubuntu/ubuntu-make#168] opened 2015-11-02 17:21 UTC
Hello,

Got a question related to installed products.
Jetbrains release [toolbox](https://www.jetbrains.com/store/) and grammatically upgrade all of the packages.
Especially [IDEA](https://www.jetbrains.com/idea/download/).
And how can I update it to 15 version?
Wait for package update or just reinstall it?

Don't found any  information about product update features.

Thanks.

**Comment by didrocks** [comment] 2015-11-03 07:54
Hey rosolko!
This is more or less a duplicate of bug #74.

The idea is typically get out of the way, meaning, letting the tool update mechanism and don't try to override anything. IIRC, Intellij's products have such a mechanism, is that not the case?

I still think we should provide something around removal/reinstall for other frameworks, but this can lead to lost configuration (if not separated from install for some tools) or plugins and such… I guess the general case should work fine as they follow best practice, but you can't provide something generic for sure.

So, I would say, for your case, I would just reinstall (umake should always pick latest available version) to do the update, does it make sense to you?

**Comment by rosolko** [comment] 2015-11-03 10:17
Hi, thanks for answer.

For first - sorry for duplicate message.

Gut get few point for now:
1. Intellij's products update mechanism isn't work for major versions. For any of the products and platform, and this is sadly.
2. Reinstall (umake should always pick latest available version) - I try this solution in the evening. Reply later.
3. it may be worth thinking about something about version control. When you perform umake to check if current version of installed product equal to installation candidate. But it wiil be hard to track this version. (It's just possible ideal solution)

Thanks.

**Comment by rosolko** [comment] 2015-11-03 16:49
Reinstall method work well, got IDEA 15 version for now. Thanks for the answer.

**Comment by didrocks** [comment] 2015-11-03 16:55
yw! as the ideas and challenges are already captured on the other bug report, closing this one then.

Thanks for your feedback :)

**Closed by didrocks** 2015-11-03 16:55 UTC
