### ISSUE TITLE
Intermittent progressbar crash (ValueError: Value out of range)

### ISSUE THREAD

**Issue by pjdelport** [ubuntu/ubuntu-make#123] opened 2015-07-08 21:36 UTC
On a fresh installation of Ubuntu 15.04, after doing the usual system package updates, my first attempt at installing PyCharm failed with the following crash:

```
piet:~$ umake ide pycharm
Choose installation path: /home/piet/tools/ide/pycharm
Downloading and installing requirements                                                                                                              |
ERROR: Unhandled exception########################################################################################################################## |
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 154, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 262, in get_progress
    self.pbar.update(progress)
  File "/usr/lib/python3/dist-packages/progressbar/__init__.py", line 271, in update
    raise ValueError('Value out of range')
ValueError: Value out of range
piet:~$
```

However, re-running `umake ide pycharm` completes the installation successfully.

I can only offer some speculation about the cause:

1. I *might* have resized the terminal window during the first run, so my first guess was that the progressbar library might have a SIGWINCH-related bug in its range calculation. However, glancing at the code, it doesn't look like its `self.maxval` gets touched by SIGWINCH, so this seems unlikely.
2. My next guess is that `BaseInstaller.get_progress()`'s tricky calculation of the progress value might sometimes be overshooting the default `maxval`: perhaps due to some edge case in updating the download progress values, or even due to float rounding?

Package versions:

* python3-apt: 0.9.3.11build1
* python3-argcomplete: 0.8.1-0ubuntu1
* python3-bs4: 4.3.2-2ubuntu2
* python3-gi: 3.14.0-1
* python3-pexpect: 3.2-1
* python3-progressbar: 2.3-1
* python3-requests: 2.4.3-6
* python3-xdg: 0.25-4
* python3-yaml: 3.11-2
* python3: 3.4.3-1
* ubuntu-make: 0.6.2

**Comment by pjdelport** [comment] 2015-07-08 21:37
#75 seems to be either the same bug, or closely related.

**Comment by didrocks** [comment] 2015-07-16 23:09
Hey pjdelport, sorry for the late reply, I was on holidays until today :)

Thanks for the detailed bug report, including as well package information and your findings, really helpful! I couldn't reproduce it with resizing the terminal and as you told, as python progressbar module doesn't support SIGWINCH, the result is not really pretty, but at least, robust. It seems you are quite on the right path with your second suggestion about get_progress() overshooting the default maxval.

I'm happy to merge an easy pull request (as you looked at it, I think you should get this credit ;)) capping the progress value. Interested?
 It would be awesome if we could reproduce it in an easy way of course though.

**Comment by pjdelport** [comment] 2015-07-16 23:49
I'll see if I can hack on this this weekend!

I agree that it would definitely help to reproduce the crash reliably, first. I don't want to cap the progress value without understanding or knowing that it actually fixes the problem. :)

**Comment by didrocks** [comment] 2015-09-01 08:14
This was is now fixed and capped

**Closed** 2015-09-01 08:13 UTC

**Comment by pjdelport** [comment] 2015-09-01 19:07
Cool, thanks!
