### ISSUE TITLE
umake ide eclipse - ERROR: Download page changed its syntax or is not parsable

### ISSUE THREAD

**Issue by TomaszDom** [ubuntu/ubuntu-make#568] opened 2018-08-16 05:07 UTC
Ubuntu 16.04.5, 18.05+201807210802~ubuntu16.04.1, also tried master branch with same results (18.05-25-g0b53f5f).

`umake -v ide eclipse
INFO: Logging level set to INFO
INFO: Create a new apt cache
INFO: clang isn't installed
INFO: No configuration file found
INFO: android-sdk-platform-tools-common isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
INFO: libbsd-dev isn't installed
INFO: libedit-dev isn't installed
INFO: libevent-dev isn't installed
INFO: libevent-core-2.0-5 isn't installed
INFO: libevent-core-2.1-6 isn't installed
INFO: libevent-core-2.0-5 | libevent-core-2.1-6 isn't installed
INFO: libevent-extra-2.0-5 isn't installed
INFO: libevent-extra-2.1-6 isn't installed
INFO: libevent-extra-2.0-5 | libevent-extra-2.1-6 isn't installed
INFO: libevent-openssl-2.0-5 isn't installed
INFO: libevent-openssl-2.1-6 isn't installed
INFO: libevent-openssl-2.0-5 | libevent-openssl-2.1-6 isn't installed
INFO: libevent-pthreads-2.0-5 isn't installed
INFO: libevent-pthreads-2.1-6 isn't installed
INFO: libevent-pthreads-2.0-5 | libevent-pthreads-2.1-6 isn't installed
INFO: libgmp-dev isn't installed
INFO: libgmpxx4ldbl isn't installed
INFO: libssl-dev isn't installed
INFO: libxml2-dev isn't installed
INFO: libyaml-dev isn't installed
INFO: libreadline-dev isn't installed
INFO: automake isn't installed
INFO: libtool isn't installed
INFO: llvm isn't installed
INFO: libpcre3-dev isn't installed
INFO: libgc-dev isn't installed
INFO: Don't register Dart Editor as it's not installable on this configuration.
INFO: libxtst6:i386 isn't installed
INFO: libxext6:i386 isn't installed
INFO: libxi6:i386 isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libxt6:i386 isn't installed
INFO: libxpm4:i386 isn't installed
INFO: libxmu6:i386 isn't installed
INFO: libgtk2.0-0:i386 isn't installed
INFO: libatk1.0-0:i386 isn't installed
INFO: libc6:i386 isn't installed
INFO: libcairo2:i386 isn't installed
INFO: libexpat1:i386 isn't installed
INFO: libfontconfig1:i386 isn't installed
INFO: libfreetype6:i386 isn't installed
INFO: libglib2.0-0:i386 isn't installed
INFO: libice6:i386 isn't installed
INFO: libpango1.0-0:i386 isn't installed
INFO: libpng12-0:i386 isn't installed
INFO: libsm6:i386 isn't installed
INFO: libxau6:i386 isn't installed
INFO: libxcursor1:i386 isn't installed
INFO: libxdmcp6:i386 isn't installed
INFO: libxfixes3:i386 isn't installed
INFO: libx11-6:i386 isn't installed
INFO: libxinerama1:i386 isn't installed
INFO: libxrandr2:i386 isn't installed
INFO: libxrender1:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: libnss3-1d:i386 isn't installed
INFO: libnspr4-0d:i386 isn't installed
INFO: libcurl3:i386 isn't installed
INFO: libasound2:i386 isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-8-jre-headless isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: mono-devel isn't installed
INFO: ruby isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jre isn't installed
INFO: openjdk-8-jre isn't installed
INFO: openjdk-7-jre | openjdk-8-jre isn't installed
INFO: openjdk-7-jre isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jre isn't installed
INFO: openjdk-8-jre isn't installed
INFO: openjdk-7-jre | openjdk-8-jre isn't installed
INFO: openjdk-7-jre isn't available on this platform
INFO: clang isn't installed
INFO: libicu-dev isn't installed
INFO: libicu57 isn't installed
INFO: Logging level set to INFO
INFO: Create a new apt cache
INFO: clang isn't installed
INFO: No configuration file found
INFO: android-sdk-platform-tools-common isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
INFO: libbsd-dev isn't installed
INFO: libedit-dev isn't installed
INFO: libevent-dev isn't installed
INFO: libevent-core-2.0-5 isn't installed
INFO: libevent-core-2.1-6 isn't installed
INFO: libevent-core-2.0-5 | libevent-core-2.1-6 isn't installed
INFO: libevent-extra-2.0-5 isn't installed
INFO: libevent-extra-2.1-6 isn't installed
INFO: libevent-extra-2.0-5 | libevent-extra-2.1-6 isn't installed
INFO: libevent-openssl-2.0-5 isn't installed
INFO: libevent-openssl-2.1-6 isn't installed
INFO: libevent-openssl-2.0-5 | libevent-openssl-2.1-6 isn't installed
INFO: libevent-pthreads-2.0-5 isn't installed
INFO: libevent-pthreads-2.1-6 isn't installed
INFO: libevent-pthreads-2.0-5 | libevent-pthreads-2.1-6 isn't installed
INFO: libgmp-dev isn't installed
INFO: libgmpxx4ldbl isn't installed
INFO: libssl-dev isn't installed
INFO: libxml2-dev isn't installed
INFO: libyaml-dev isn't installed
INFO: libreadline-dev isn't installed
INFO: automake isn't installed
INFO: libtool isn't installed
INFO: llvm isn't installed
INFO: libpcre3-dev isn't installed
INFO: libgc-dev isn't installed
INFO: Don't register Dart Editor as it's not installable on this configuration.
INFO: libxtst6:i386 isn't installed
INFO: libxext6:i386 isn't installed
INFO: libxi6:i386 isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libxt6:i386 isn't installed
INFO: libxpm4:i386 isn't installed
INFO: libxmu6:i386 isn't installed
INFO: libgtk2.0-0:i386 isn't installed
INFO: libatk1.0-0:i386 isn't installed
INFO: libc6:i386 isn't installed
INFO: libcairo2:i386 isn't installed
INFO: libexpat1:i386 isn't installed
INFO: libfontconfig1:i386 isn't installed
INFO: libfreetype6:i386 isn't installed
INFO: libglib2.0-0:i386 isn't installed
INFO: libice6:i386 isn't installed
INFO: libpango1.0-0:i386 isn't installed
INFO: libpng12-0:i386 isn't installed
INFO: libsm6:i386 isn't installed
INFO: libxau6:i386 isn't installed
INFO: libxcursor1:i386 isn't installed
INFO: libxdmcp6:i386 isn't installed
INFO: libxfixes3:i386 isn't installed
INFO: libx11-6:i386 isn't installed
INFO: libxinerama1:i386 isn't installed
INFO: libxrandr2:i386 isn't installed
INFO: libxrender1:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: libnss3-1d:i386 isn't installed
INFO: libnspr4-0d:i386 isn't installed
INFO: libcurl3:i386 isn't installed
INFO: libasound2:i386 isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-8-jre-headless isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: mono-devel isn't installed
INFO: ruby isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jre isn't installed
INFO: openjdk-8-jre isn't installed
INFO: openjdk-7-jre | openjdk-8-jre isn't installed
INFO: openjdk-7-jre isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jre isn't installed
INFO: openjdk-8-jre isn't installed
INFO: openjdk-7-jre | openjdk-8-jre isn't installed
INFO: openjdk-7-jre isn't available on this platform
INFO: clang isn't installed
INFO: libicu-dev isn't installed
INFO: libicu57 isn't installed
Choose installation path: /home/vagrant/.local/share/umake/ide/eclipse
INFO: Start downloading DownloadItem(url='https://www.eclipse.org/downloads/eclipse-packages/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): www.eclipse.org
INFO: https://www.eclipse.org/downloads/eclipse-packages/ download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org/downloads/eclipse-packages/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None)] done
ERROR: Download page changed its syntax or is not parsable
INFO: Starting new HTTPS connection (1): github.com`

**Comment by LyzardKing** [comment] 2018-08-16 07:40
This is a duplicate of #565.
Also there is a branch and a pr with the fix.
It still needs fixing, and at the moment I'm unable to test this properly.
All the help we can get is welcome.
The PR is #564

**Closed by LyzardKing** 2018-08-16 07:40 UTC
