### ISSUE TITLE
Install bug: exception of progress bar

### ISSUE THREAD

**Issue by Seha16** [ubuntu/ubuntu-make#127] opened 2015-07-25 21:49 UTC
During installing and android sdk by command: "umake android" sometimes generate exception. 
Please could you catch this exception?

[I Accept (a)/I don't accept (N)] a
Downloading and installing requirements                                        |
ERROR: Unhandled exception#################################################### |
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 154, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 261, in get_progress
    self.pbar.update(progress)
  File "/usr/lib/python3/dist-packages/progressbar/\__init\__.py", line 271, in update
    raise ValueError('Value out of range')
ValueError: Value out of range

**Comment by didrocks** [comment] 2015-07-27 07:07
Thanks for your bug report and helping Ubuntu Make to be better!

It seems to me to be a duplicate of bug #123, so I'm closing that one. There is an easy fix (but it would interesting to know under which conditions this out of cap value triggers) that pjdelport is going to proceed, do not hesitate however if you have any idea to reliably raise this exception, we are particularly interested :)

**Closed by didrocks** 2015-07-27 07:07 UTC
